"""
Adjective Declension (Adjektivdeklination) — Exercise Bank.

Tests adjective endings after bestimmter/unbestimmter Artikel, possessives,
without article (starke Deklination), Genitiv, and multiple adjectives.
Exercise type: gap_fill
"""

ADJEKTIVE_BANK = [
    {'id': 'gen_adj_001', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Ich sehe den alt{gap_1} Mann im Park.', 'gaps': [{'position': 'gap_1', 'context': 'alt__', 'answer': 'en', 'article_type': 'bestimmt', 'case': 'Akkusativ', 'gender': 'maskulin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Ich sehe den alten Mann im Park.'}, 'grammar_rule': 'After bestimmter Artikel, Akkusativ maskulin -> -en', 'grammar_tip': 'Der-Wörter im Akkusativ maskulin bekommen immer -en.'},
    {'id': 'gen_adj_002', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Die nett{gap_1} Nachbarin hilft mir oft.', 'gaps': [{'position': 'gap_1', 'context': 'nett__', 'answer': 'e', 'article_type': 'bestimmt', 'case': 'Nominativ', 'gender': 'feminin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Die nette Nachbarin hilft mir oft.'}, 'grammar_rule': 'After bestimmter Artikel, Nominativ feminin -> -e', 'grammar_tip': 'Die + Nominativ feminin = -e.'},
    {'id': 'gen_adj_003', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Das klein{gap_1} Kind spielt im Garten.', 'gaps': [{'position': 'gap_1', 'context': 'klein__', 'answer': 'e', 'article_type': 'bestimmt', 'case': 'Nominativ', 'gender': 'neutrum', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Das kleine Kind spielt im Garten.'}, 'grammar_rule': 'After bestimmter Artikel, Nominativ neutrum -> -e', 'grammar_tip': 'Das + Nominativ = -e.'},
    {'id': 'gen_adj_004', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Ich kaufe die frisch{gap_1} Erdbeeren.', 'gaps': [{'position': 'gap_1', 'context': 'frisch__', 'answer': 'en', 'article_type': 'bestimmt', 'case': 'Akkusativ', 'gender': 'plural', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Ich kaufe die frischen Erdbeeren.'}, 'grammar_rule': 'After bestimmter Artikel, Akkusativ plural -> -en', 'grammar_tip': 'Im Plural mit der-Wörtern fast immer -en.'},
    {'id': 'gen_adj_005', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Wir besuchen das neu{gap_1} Museum.', 'gaps': [{'position': 'gap_1', 'context': 'neu__', 'answer': 'e', 'article_type': 'bestimmt', 'case': 'Akkusativ', 'gender': 'neutrum', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Wir besuchen das neue Museum.'}, 'grammar_rule': 'After bestimmter Artikel, Akkusativ neutrum -> -e', 'grammar_tip': 'Das bleibt -e im Nominativ und Akkusativ.'},
    {'id': 'gen_adj_006', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Der jung{gap_1} Student lernt viel.', 'gaps': [{'position': 'gap_1', 'context': 'jung__', 'answer': 'e', 'article_type': 'bestimmt', 'case': 'Nominativ', 'gender': 'maskulin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Der junge Student lernt viel.'}, 'grammar_rule': 'After bestimmter Artikel, Nominativ maskulin -> -e', 'grammar_tip': 'Der im Nominativ braucht -e.'},
    {'id': 'gen_adj_007', 'module': 'adjektive', 'type': 'gap_fill', 'level': 1, 'topic': 'adj_bestimmt', 'data': {'sentence_template': 'Ich nehme die groß{gap_1} Tasche mit.', 'gaps': [{'position': 'gap_1', 'context': 'groß__', 'answer': 'e', 'article_type': 'bestimmt', 'case': 'Akkusativ', 'gender': 'feminin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Ich nehme die große Tasche mit.'}, 'grammar_rule': 'After bestimmter Artikel, Akkusativ feminin -> -e', 'grammar_tip': 'Die bleibt -e in Nom und Akk.'},
    {'id': 'gen_adj_008', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_unbestimmt', 'data': {'sentence_template': 'Ein alt{gap_1} Baum steht vor dem Haus.', 'gaps': [{'position': 'gap_1', 'context': 'alt__', 'answer': 'er', 'article_type': 'unbestimmt', 'case': 'Nominativ', 'gender': 'maskulin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Ein alter Baum steht vor dem Haus.'}, 'grammar_rule': 'After ein-Wort, Nominativ maskulin -> -er', 'grammar_tip': 'Fehlt die Endung am Artikel, zeigt sie das Adjektiv.'},
    {'id': 'gen_adj_009', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_unbestimmt', 'data': {'sentence_template': 'Ich trinke ein kalt{gap_1} Wasser.', 'gaps': [{'position': 'gap_1', 'context': 'kalt__', 'answer': 'es', 'article_type': 'unbestimmt', 'case': 'Akkusativ', 'gender': 'neutrum', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Ich trinke ein kaltes Wasser.'}, 'grammar_rule': 'After ein-Wort, Akkusativ neutrum -> -es', 'grammar_tip': 'Ein (ohne Endung) braucht starkes -es.'},
    {'id': 'gen_adj_010', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_possessiv', 'data': {'sentence_template': 'Meine neu{gap_1} Wohnung ist sehr hell.', 'gaps': [{'position': 'gap_1', 'context': 'neu__', 'answer': 'e', 'article_type': 'possessiv', 'case': 'Nominativ', 'gender': 'feminin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Meine neue Wohnung ist sehr hell.'}, 'grammar_rule': 'After possessiv, Nominativ feminin -> -e', 'grammar_tip': 'Meine funktioniert wie eine.'},
    {'id': 'gen_adj_011', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_possessiv', 'data': {'sentence_template': 'Mit meinem neu{gap_1} Fahrrad fahre ich zur Arbeit.', 'gaps': [{'position': 'gap_1', 'context': 'neu__', 'answer': 'en', 'article_type': 'possessiv', 'case': 'Dativ', 'gender': 'neutrum', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Mit meinem neuen Fahrrad fahre ich zur Arbeit.'}, 'grammar_rule': 'After possessiv, Dativ -> -en', 'grammar_tip': 'Im Dativ fast immer -en.'},
    {'id': 'gen_adj_012', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_unbestimmt', 'data': {'sentence_template': 'Er wohnt in einer schön{gap_1} Stadt.', 'gaps': [{'position': 'gap_1', 'context': 'schön__', 'answer': 'en', 'article_type': 'unbestimmt', 'case': 'Dativ', 'gender': 'feminin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Er wohnt in einer schönen Stadt.'}, 'grammar_rule': 'After ein-Wort, Dativ feminin -> -en', 'grammar_tip': 'Dativ = -en.'},
    {'id': 'gen_adj_013', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_unbestimmt', 'data': {'sentence_template': 'Sie hat einen interessant{gap_1} Job gefunden.', 'gaps': [{'position': 'gap_1', 'context': 'interessant__', 'answer': 'en', 'article_type': 'unbestimmt', 'case': 'Akkusativ', 'gender': 'maskulin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Sie hat einen interessanten Job gefunden.'}, 'grammar_rule': 'After ein-Wort, Akkusativ maskulin -> -en', 'grammar_tip': 'Einen + maskulin = -en.'},
    {'id': 'gen_adj_014', 'module': 'adjektive', 'type': 'gap_fill', 'level': 2, 'topic': 'adj_possessiv', 'data': {'sentence_template': 'Ich danke meinem hilfsbereit{gap_1} Kollegen.', 'gaps': [{'position': 'gap_1', 'context': 'hilfsbereit__', 'answer': 'en', 'article_type': 'possessiv', 'case': 'Dativ', 'gender': 'maskulin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Ich danke meinem hilfsbereiten Kollegen.'}, 'grammar_rule': 'After possessiv, Dativ maskulin -> -en', 'grammar_tip': 'Dativ maskulin braucht -en.'},
    {'id': 'gen_adj_015', 'module': 'adjektive', 'type': 'gap_fill', 'level': 3, 'topic': 'adj_ohne_artikel', 'data': {'sentence_template': 'Frisch{gap_1} Brot schmeckt am besten am Morgen.', 'gaps': [{'position': 'gap_1', 'context': 'Frisch__', 'answer': 'es', 'article_type': 'ohne', 'case': 'Nominativ', 'gender': 'neutrum', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Frisches Brot schmeckt am besten am Morgen.'}, 'grammar_rule': 'Without article, Nominativ neutrum -> -es', 'grammar_tip': 'Ohne Artikel übernimmt das Adjektiv die starke Endung.'},
    {'id': 'gen_adj_016', 'module': 'adjektive', 'type': 'gap_fill', 'level': 3, 'topic': 'adj_ohne_artikel', 'data': {'sentence_template': 'Mit gut{gap_1} Freunden reist man gern.', 'gaps': [{'position': 'gap_1', 'context': 'gut__', 'answer': 'en', 'article_type': 'ohne', 'case': 'Dativ', 'gender': 'plural', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Mit guten Freunden reist man gern.'}, 'grammar_rule': 'Without article, Dativ plural -> -en', 'grammar_tip': 'Dativ Plural immer -en.'},
    {'id': 'gen_adj_017', 'module': 'adjektive', 'type': 'gap_fill', 'level': 3, 'topic': 'adj_genitiv', 'data': {'sentence_template': 'Wegen stark{gap_1} Regens fiel das Konzert aus.', 'gaps': [{'position': 'gap_1', 'context': 'stark__', 'answer': 'en', 'article_type': 'ohne', 'case': 'Genitiv', 'gender': 'maskulin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Wegen starken Regens fiel das Konzert aus.'}, 'grammar_rule': 'Without article, Genitiv maskulin -> -en', 'grammar_tip': 'Genitiv maskulin stark = -en.'},
    {'id': 'gen_adj_018', 'module': 'adjektive', 'type': 'gap_fill', 'level': 3, 'topic': 'adj_multiple', 'data': {'sentence_template': 'Alt{gap_1}, historisch{gap_2} Gebäude prägen das Stadtbild.', 'gaps': [{'position': 'gap_1', 'context': 'Alt__', 'answer': 'e', 'article_type': 'ohne', 'case': 'Nominativ', 'gender': 'plural', 'options': ['e', 'en', 'er', 'es', 'em']}, {'position': 'gap_2', 'context': 'historisch__', 'answer': 'e', 'article_type': 'ohne', 'case': 'Nominativ', 'gender': 'plural', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Alte, historische Gebäude prägen das Stadtbild.'}, 'grammar_rule': 'Without article, Nominativ plural -> -e', 'grammar_tip': 'Mehrere Adjektive bekommen die gleiche starke Endung.'},
    {'id': 'gen_adj_019', 'module': 'adjektive', 'type': 'gap_fill', 'level': 3, 'topic': 'adj_ohne_artikel', 'data': {'sentence_template': 'Kalt{gap_1} Winter können sehr hart sein.', 'gaps': [{'position': 'gap_1', 'context': 'Kalt__', 'answer': 'e', 'article_type': 'ohne', 'case': 'Nominativ', 'gender': 'plural', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Kalte Winter können sehr hart sein.'}, 'grammar_rule': 'Without article, Nominativ plural -> -e', 'grammar_tip': 'Ohne Artikel zeigt das Adjektiv den Kasus.'},
    {'id': 'gen_adj_020', 'module': 'adjektive', 'type': 'gap_fill', 'level': 3, 'topic': 'adj_genitiv', 'data': {'sentence_template': 'Trotz groß{gap_1} Hitze gingen wir spazieren.', 'gaps': [{'position': 'gap_1', 'context': 'groß__', 'answer': 'er', 'article_type': 'ohne', 'case': 'Genitiv', 'gender': 'feminin', 'options': ['e', 'en', 'er', 'es', 'em']}], 'full_correct': 'Trotz großer Hitze gingen wir spazieren.'}, 'grammar_rule': 'Without article, Genitiv feminin -> -er', 'grammar_tip': 'Genitiv feminin stark = -er.'},
]

