"""
Konjunktiv II / Subjunctive Mood — Exercise Bank.

Tests würde+Infinitiv, wenn-clauses with hätte/wäre,
Konjunktiv II Vergangenheit, als ob + Konjunktiv,
and Konjunktiv I (indirect speech).
Exercise types: reconstruction + gap_fill
"""

KONJUNKTIV_BANK = [
    {'id': 'gen_konj_001', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Ich würde mehr reisen, wenn ich genug Geld hätte.', 'english': 'I would travel more if I had enough money.', 'verbs': ['würde', 'reisen', 'hätte'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Konjunktiv II mit würde + Infinitiv drückt eine irreale Situation aus; im wenn-Satz steht hätte am Ende.', 'grammar_tip': 'Irreal = würde + Infinitiv, wenn + hätte/wäre.'},
    {'id': 'gen_konj_002', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn ich mehr Zeit hätte, würde ich ein Buch schreiben.', 'english': 'If I had more time, I would write a book.', 'verbs': ['hätte', 'würde', 'schreiben'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Im irrealen Bedingungssatz steht hätte im Nebensatz und würde + Infinitiv im Hauptsatz.', 'grammar_tip': 'Wenn + hätte, dann würde.'},
    {'id': 'gen_konj_003', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn er früher käme, wären wir pünktlich.', 'english': 'If he came earlier, we would be on time.', 'verbs': ['käme', 'wären'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Starke Verben bilden eigene Konjunktiv-II-Formen wie käme und wären.', 'grammar_tip': 'Irreal = Umlaut + -e.'},
    {'id': 'gen_konj_004', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wunsch', 'data': {'text': 'Ich wünschte, ich wäre jetzt am Meer.', 'english': 'I wish I were at the sea right now.', 'verbs': ['wünschte', 'wäre'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Wünsche werden mit Konjunktiv II ausgedrückt, oft mit wäre oder hätte.', 'grammar_tip': 'Wunsch = wäre/hätte.'},
    {'id': 'gen_konj_005', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Er würde dir helfen, wenn du ihn fragen würdest.', 'english': 'He would help you if you asked him.', 'verbs': ['würde', 'helfen', 'würdest', 'fragen'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'In beiden Teilsätzen steht Konjunktiv II zur Darstellung einer hypothetischen Situation.', 'grammar_tip': 'würde im Hauptsatz, würdest im Nebensatz.'},
    {'id': 'gen_konj_006', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn ich du wäre, würde ich das Angebot annehmen.', 'english': 'If I were you, I would accept the offer.', 'verbs': ['wäre', 'würde', 'annehmen'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Bei Ratschlägen steht wäre im wenn-Satz und würde + Infinitiv im Hauptsatz.', 'grammar_tip': 'Wenn ich du wäre ...'},
    {'id': 'gen_konj_007', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Ich hätte dich angerufen, wenn ich deine Nummer gehabt hätte.', 'english': 'I would have called you if I had had your number.', 'verbs': ['hätte', 'angerufen', 'gehabt', 'hätte'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Konjunktiv II Vergangenheit wird mit hätte/wäre + Partizip II gebildet.', 'grammar_tip': 'Vergangenheit irreal = hätte + Partizip.'},
    {'id': 'gen_konj_008', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn sie früher gegangen wäre, hätte sie den Zug erreicht.', 'english': 'If she had left earlier, she would have caught the train.', 'verbs': ['gegangen', 'wäre', 'hätte', 'erreicht'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Im irrealen Vergangenheitssatz stehen wäre oder hätte + Partizip II.', 'grammar_tip': 'wäre gegangen, hätte erreicht.'},
    {'id': 'gen_konj_009', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er tut so, als ob er alles wüsste.', 'english': 'He acts as if he knew everything.', 'verbs': ['tut', 'wüsste'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Nach als ob steht Konjunktiv II zur Beschreibung einer irreale Annahme.', 'grammar_tip': 'Als ob = Konjunktiv II.'},
    {'id': 'gen_konj_010', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Sie spricht, als ob sie Expertin wäre.', 'english': 'She speaks as if she were an expert.', 'verbs': ['spricht', 'wäre'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Als-ob-Sätze stehen im Konjunktiv II, da sie eine irreale Vorstellung ausdrücken.', 'grammar_tip': 'Als ob + wäre.'},
    {'id': 'gen_konj_011', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Er hätte mehr gelernt, wenn er nicht so müde gewesen wäre.', 'english': 'He would have studied more if he had not been so tired.', 'verbs': ['hätte', 'gelernt', 'gewesen', 'wäre'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Irreale Vergangenheit nutzt hätte/wäre + Partizip II.', 'grammar_tip': 'gewesen wäre.'},
    {'id': 'gen_konj_012', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn wir früher gestartet wären, hätten wir den Stau vermieden.', 'english': 'If we had started earlier, we would have avoided the traffic jam.', 'verbs': ['gestartet', 'wären', 'hätten', 'vermieden'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Beide Teilsätze stehen im Konjunktiv II Vergangenheit.', 'grammar_tip': 'wären gestartet, hätten vermieden.'},
    {'id': 'gen_konj_013', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Er sagte, er {gap_1} krank.', 'gaps': [{'position': 'gap_1', 'context': 'er ___ krank', 'answer': 'sei', 'options': ['ist', 'sei', 'wäre', 'war', 'sein'], 'indicative_hint': 'er ist -> Konjunktiv I?'}], 'full_correct': 'Er sagte, er sei krank.', 'english': 'He said that he was ill.'}, 'grammar_rule': 'Konjunktiv I wird für indirekte Rede verwendet.', 'grammar_tip': 'Indirekte Rede = sei, habe, gehe.'},
    {'id': 'gen_konj_014', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Sie meinte, sie {gap_1} keine Zeit.', 'gaps': [{'position': 'gap_1', 'context': 'sie ___ keine Zeit', 'answer': 'habe', 'options': ['hat', 'habe', 'hätte', 'hatte', 'haben'], 'indicative_hint': 'sie hat -> Konjunktiv I?'}], 'full_correct': 'Sie meinte, sie habe keine Zeit.', 'english': 'She said that she had no time.'}, 'grammar_rule': 'In der indirekten Rede steht Konjunktiv I statt Indikativ.', 'grammar_tip': 'habe statt hat.'},
    {'id': 'gen_konj_015', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_2_spezial', 'data': {'sentence_template': 'Wenn er doch nur mehr Mut {gap_1}.', 'gaps': [{'position': 'gap_1', 'context': 'er ___ mehr Mut', 'answer': 'hätte', 'options': ['hat', 'hätte', 'habe', 'hatte', 'haben'], 'indicative_hint': 'er hat -> Wunsch?'}], 'full_correct': 'Wenn er doch nur mehr Mut hätte.', 'english': 'If only he had more courage.'}, 'grammar_rule': 'Konjunktiv II drückt einen unerfüllbaren Wunsch aus.', 'grammar_tip': 'Doch nur + hätte.'},
    {'id': 'gen_konj_016', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_2_spezial', 'data': {'sentence_template': 'Er tat, als {gap_1} er alles gewusst.', 'gaps': [{'position': 'gap_1', 'context': 'als ___ er', 'answer': 'hätte', 'options': ['hat', 'habe', 'hätte', 'war', 'sei'], 'indicative_hint': 'Plusquamperfekt?'}], 'full_correct': 'Er tat, als hätte er alles gewusst.', 'english': 'He acted as if he had known everything.'}, 'grammar_rule': 'Als + Konjunktiv II Vergangenheit wird mit hätte + Partizip II gebildet.', 'grammar_tip': 'als hätte er.'},
    {'id': 'gen_konj_017', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Er sagte, er hätte das Projekt beendet, wenn er mehr Unterstützung bekommen hätte.', 'english': 'He said he would have finished the project if he had received more support.', 'verbs': ['hätte', 'beendet', 'bekommen', 'hätte'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'In komplexen Sätzen stehen mehrere Konjunktiv-II-Formen für irreale Vergangenheit.', 'grammar_tip': 'Mehrfach hätte + Partizip.'},
    {'id': 'gen_konj_018', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er verhielt sich, als ob er nichts bemerkt hätte.', 'english': 'He behaved as if he had noticed nothing.', 'verbs': ['verhielt', 'hätte', 'bemerkt'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Als-ob-Sätze im Konjunktiv II Vergangenheit drücken Irrealität aus.', 'grammar_tip': 'als ob + hätte + Partizip.'},
    {'id': 'gen_konj_019', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'wunsch', 'data': {'text': 'Hätte ich doch nur besser aufgepasst, wäre das nicht passiert.', 'english': 'If only I had paid better attention, that would not have happened.', 'verbs': ['Hätte', 'aufgepasst', 'wäre', 'passiert'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Inversion mit hätte am Satzanfang drückt einen unerfüllten Wunsch aus.', 'grammar_tip': 'Hätte ich doch ...'},
    {'id': 'gen_konj_020', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn er nicht so spät gekommen wäre, hätte er den Vortrag noch hören können.', 'english': 'If he had not arrived so late, he would still have been able to hear the lecture.', 'verbs': ['gekommen', 'wäre', 'hätte', 'hören', 'können'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Komplexer irrealer Bedingungssatz mit Konjunktiv II Vergangenheit im Nebensatz und Hauptsatz.', 'grammar_tip': 'wäre gekommen, hätte hören können.'},
]

KONJUNKTIV_BANK.extend([
    # LEVEL 2 (021–030)
    {'id': 'gen_konj_021', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Ich würde heute länger schlafen, wenn ich morgen frei hätte.', 'english': 'I would sleep longer today if I had tomorrow off.', 'verbs': ['würde', 'schlafen', 'hätte'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Konjunktiv II mit würde + Infinitiv beschreibt eine nicht reale Möglichkeit.', 'grammar_tip': 'würde + Infinitiv im Hauptsatz, hätte/wäre im Nebensatz.'},
    {'id': 'gen_konj_022', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn wir näher an der Stadt wohnten, würden wir öfter ausgehen.', 'english': 'If we lived closer to the city, we would go out more often.', 'verbs': ['wohnten', 'würden', 'ausgehen'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Irreale Bedingungen stehen oft mit wenn + Konjunktiv II.', 'grammar_tip': 'Wenn + Konjunktiv II, dann würde + Infinitiv.'},
    {'id': 'gen_konj_023', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wunsch', 'data': {'text': 'Ich wünschte, du wärst jetzt hier.', 'english': 'I wish you were here now.', 'verbs': ['wünschte', 'wärst'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Mit Konjunktiv II drückt man Wünsche aus, die nicht erfüllt sind.', 'grammar_tip': 'Wunschformen: wäre, hätte, könnte.'},
    {'id': 'gen_konj_024', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn ich besser Deutsch spräche, könnte ich dort arbeiten.', 'english': 'If I spoke German better, I could work there.', 'verbs': ['spräche', 'könnte', 'arbeiten'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Einige Verben haben eigene Konjunktiv-II-Formen wie spräche oder könnte.', 'grammar_tip': 'Starke Verben oft mit Umlaut im Konjunktiv II.'},
    {'id': 'gen_konj_025', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Sie würde das Auto kaufen, wenn es billiger wäre.', 'english': 'She would buy the car if it were cheaper.', 'verbs': ['würde', 'kaufen', 'wäre'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Der Hauptsatz zeigt die Folge einer irrealen Bedingung.', 'grammar_tip': 'würde kaufen, wenn es billiger wäre.'},
    {'id': 'gen_konj_026', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn du früher aufstündest, hättest du weniger Stress.', 'english': 'If you got up earlier, you would have less stress.', 'verbs': ['aufstündest', 'hättest'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Konjunktiv II kann mit einfachen Formen wie hättest oder aufstündest gebildet werden.', 'grammar_tip': 'Irrealer Rat: Wenn du ..., hättest du ...'},
    {'id': 'gen_konj_027', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wunsch', 'data': {'text': 'Ach, hätte ich doch mehr Geduld!', 'english': 'If only I had more patience!', 'verbs': ['hätte'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Kurze Wunschäußerungen stehen oft mit hätte oder wäre.', 'grammar_tip': 'Ach, hätte ich doch ...'},
    {'id': 'gen_konj_028', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Wir würden gern umziehen, wenn die Miete niedriger wäre.', 'english': 'We would like to move if the rent were lower.', 'verbs': ['würden', 'umziehen', 'wäre'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'würde + Infinitiv ist besonders häufig in der gesprochenen Sprache.', 'grammar_tip': 'würden gern + Infinitiv = höflich oder irreal.'},
    {'id': 'gen_konj_029', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn er mehr trainierte, wäre er fitter.', 'english': 'If he trained more, he would be fitter.', 'verbs': ['trainierte', 'wäre'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Irreale Aussagen über die Gegenwart stehen im Konjunktiv II.', 'grammar_tip': 'Wenn + Präteritumform, dann wäre/würde ...'},
    {'id': 'gen_konj_030', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn ich ihr die Wahrheit sagte, wäre sie enttäuscht.', 'english': 'If I told her the truth, she would be disappointed.', 'verbs': ['sagte', 'wäre'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Der Konjunktiv II zeigt hier eine vorgestellte, nicht reale Situation.', 'grammar_tip': 'sagte / wäre = irreal in der Gegenwart.'},

    # LEVEL 3 (031–040)
    {'id': 'gen_konj_031', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Ich wäre mitgekommen, wenn ich früher zu Hause gewesen wäre.', 'english': 'I would have come along if I had been home earlier.', 'verbs': ['wäre', 'mitgekommen', 'gewesen', 'wäre'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Konjunktiv II Vergangenheit wird mit wäre/hätte + Partizip II gebildet.', 'grammar_tip': 'wäre mitgekommen, gewesen wäre.'},
    {'id': 'gen_konj_032', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er schaut mich an, als ob er mich erkennen würde.', 'english': 'He looks at me as if he would recognize me.', 'verbs': ['schaut', 'würde', 'erkennen'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Nach als ob steht oft Konjunktiv II, um Irrealität auszudrücken.', 'grammar_tip': 'als ob + Konjunktiv II.'},
    {'id': 'gen_konj_033', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn du mich informiert hättest, hätte ich dir geholfen.', 'english': 'If you had informed me, I would have helped you.', 'verbs': ['informiert', 'hättest', 'hätte', 'geholfen'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'In irrealen Vergangenheitssätzen stehen beide Teilsätze im Konjunktiv II Vergangenheit.', 'grammar_tip': 'hättest informiert, hätte geholfen.'},
    {'id': 'gen_konj_034', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Sie lächelt, als ob alles in Ordnung wäre.', 'english': 'She smiles as if everything were fine.', 'verbs': ['lächelt', 'wäre'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Als-ob-Sätze beschreiben etwas, das nur so scheint.', 'grammar_tip': 'als ob + wäre / hätte / würde.'},
    {'id': 'gen_konj_035', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wir hätten das Problem vermieden, wenn wir besser geplant hätten.', 'english': 'We would have avoided the problem if we had planned better.', 'verbs': ['hätten', 'vermieden', 'geplant', 'hätten'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Mit hätten + Partizip II beschreibt man irreale Folgen in der Vergangenheit.', 'grammar_tip': 'hätten vermieden, hätten geplant.'},
    {'id': 'gen_konj_036', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'wunsch', 'data': {'text': 'Wäre das Wetter doch nur besser gewesen!', 'english': 'If only the weather had been better!', 'verbs': ['Wäre', 'gewesen'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Unerfüllte Wünsche über die Vergangenheit stehen im Konjunktiv II Vergangenheit.', 'grammar_tip': 'Wäre ... doch nur gewesen!'},
    {'id': 'gen_konj_037', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er redete, als ob er den Film schon gesehen hätte.', 'english': 'He spoke as if he had already seen the film.', 'verbs': ['redete', 'hätte', 'gesehen'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Für irreale Vorvergangenheit nach als ob nutzt man hätte/wäre + Partizip II.', 'grammar_tip': 'als ob er ... gesehen hätte.'},
    {'id': 'gen_konj_038', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn ich mehr geübt hätte, wäre ich sicherer gewesen.', 'english': 'If I had practised more, I would have been more confident.', 'verbs': ['geübt', 'hätte', 'wäre', 'gewesen'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Bei Zuständen im Ergebnis steht oft wäre gewesen.', 'grammar_tip': 'hätte geübt, wäre sicherer gewesen.'},
    {'id': 'gen_konj_039', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'wunsch', 'data': {'text': 'Ich wünschte, wir hätten uns früher kennengelernt.', 'english': 'I wish we had met earlier.', 'verbs': ['wünschte', 'hätten', 'kennengelernt'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Wünsche über verpasste Möglichkeiten stehen im Konjunktiv II Vergangenheit.', 'grammar_tip': 'wünschte + hätten/wären + Partizip II.'},
    {'id': 'gen_konj_040', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Sie wäre nicht krank geworden, wenn sie sich wärmer angezogen hätte.', 'english': 'She would not have become ill if she had dressed more warmly.', 'verbs': ['wäre', 'geworden', 'angezogen', 'hätte'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Auch bei Veränderungen oder Zuständen in der Vergangenheit wird Konjunktiv II Vergangenheit verwendet.', 'grammar_tip': 'wäre geworden, hätte angezogen.'},

    # LEVEL 4 (041–050)
    {'id': 'gen_konj_041', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Der Sprecher erklärte, man {gap_1} sofort handeln.', 'gaps': [{'position': 'gap_1', 'context': 'man ___ sofort handeln', 'answer': 'müsse', 'options': ['muss', 'müsse', 'musste', 'müsste', 'müssen'], 'indicative_hint': 'man muss -> indirekte Rede?'}], 'full_correct': 'Der Sprecher erklärte, man müsse sofort handeln.', 'english': 'The speaker explained that action had to be taken immediately.'}, 'grammar_rule': 'Konjunktiv I markiert indirekte Rede und Distanz zum Gesagten.', 'grammar_tip': 'müsse statt muss.'},
    {'id': 'gen_konj_042', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Sie behauptete, der Bericht {gap_1} vollständig korrekt.', 'gaps': [{'position': 'gap_1', 'context': 'der Bericht ___ vollständig korrekt', 'answer': 'sei', 'options': ['ist', 'sei', 'wäre', 'war', 'sein'], 'indicative_hint': 'der Bericht ist -> indirekte Rede?'}], 'full_correct': 'Sie behauptete, der Bericht sei vollständig korrekt.', 'english': 'She claimed that the report was completely correct.'}, 'grammar_rule': 'In der indirekten Rede ersetzt Konjunktiv I häufig den Indikativ.', 'grammar_tip': 'sei statt ist.'},
    {'id': 'gen_konj_043', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_2_spezial', 'data': {'sentence_template': 'An deiner Stelle {gap_1} ich vorsichtiger.', 'gaps': [{'position': 'gap_1', 'context': 'ich ___ vorsichtiger', 'answer': 'wäre', 'options': ['bin', 'wäre', 'sei', 'war', 'würde'], 'indicative_hint': 'Rat geben?'}], 'full_correct': 'An deiner Stelle wäre ich vorsichtiger.', 'english': 'If I were you, I would be more careful.'}, 'grammar_rule': 'Für Ratschläge verwendet man oft feste Wendungen mit wäre.', 'grammar_tip': 'An deiner Stelle wäre ich ...'},
    {'id': 'gen_konj_044', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_2_spezial', 'data': {'sentence_template': 'Fast {gap_1} ich den Termin vergessen.', 'gaps': [{'position': 'gap_1', 'context': 'Fast ___ ich', 'answer': 'hätte', 'options': ['habe', 'hätte', 'hatte', 'wäre', 'sei'], 'indicative_hint': 'Beinahe passiert?'}], 'full_correct': 'Fast hätte ich den Termin vergessen.', 'english': 'I almost forgot the appointment.'}, 'grammar_rule': 'Fast hätte + Partizip II drückt eine beinahe eingetretene Handlung aus.', 'grammar_tip': 'Fast hätte ich ...'},
    {'id': 'gen_konj_045', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Die Zeugin sagte, sie habe den Mann nie zuvor gesehen.', 'english': 'The witness said that she had never seen the man before.', 'verbs': ['sagte', 'habe', 'gesehen'], 'clause_type': 'konjunktiv_1_vergangenheit'}, 'grammar_rule': 'Konjunktiv I Perfekt mit habe + Partizip II wird in der indirekten Rede verwendet.', 'grammar_tip': 'Indirekte Vergangenheit = habe/sei + Partizip II.'},
    {'id': 'gen_konj_046', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er antwortete, als wüsste er bereits alles.', 'english': 'He answered as if he already knew everything.', 'verbs': ['antwortete', 'wüsste'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Als-Sätze ohne ob können ebenfalls den Konjunktiv II verlangen.', 'grammar_tip': 'als wüsste er ...'},
    {'id': 'gen_konj_047', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'text': 'Der Minister erklärte, die Lage werde sich bald stabilisieren.', 'english': 'The minister stated that the situation would stabilize soon.', 'verbs': ['erklärte', 'werde', 'stabilisieren'], 'clause_type': 'konjunktiv_1'}, 'grammar_rule': 'werde + Infinitiv ist eine typische Form des Konjunktiv I in der indirekten Rede.', 'grammar_tip': 'werde + Infinitiv = Zukunft in indirekter Rede.'},
    {'id': 'gen_konj_048', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'wunsch', 'data': {'text': 'Hätte sie den Vertrag doch genauer gelesen, wäre der Fehler aufgefallen.', 'english': 'If only she had read the contract more carefully, the mistake would have been noticed.', 'verbs': ['Hätte', 'gelesen', 'wäre', 'aufgefallen'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Inversion mit hätte am Anfang betont einen starken unerfüllten Wunsch oder Vorwurf.', 'grammar_tip': 'Hätte sie doch ...'},
    {'id': 'gen_konj_049', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Der Arzt meinte, die Patientin {gap_1} sich ausruhen.', 'gaps': [{'position': 'gap_1', 'context': 'die Patientin ___ sich ausruhen', 'answer': 'solle', 'options': ['soll', 'solle', 'sollte', 'sollte sich', 'sollen'], 'indicative_hint': 'sie soll -> indirekte Rede?'}], 'full_correct': 'Der Arzt meinte, die Patientin solle sich ausruhen.', 'english': 'The doctor said that the patient should rest.'}, 'grammar_rule': 'Modalverben bilden im Konjunktiv I Formen wie solle, müsse, dürfe.', 'grammar_tip': 'solle statt soll.'},
    {'id': 'gen_konj_050', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn der Bericht früher veröffentlicht worden wäre, hätte die Öffentlichkeit anders reagiert.', 'english': 'If the report had been published earlier, the public would have reacted differently.', 'verbs': ['veröffentlicht', 'worden', 'wäre', 'hätte', 'reagiert'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Auch Passivformen können im Konjunktiv II Vergangenheit stehen: wäre + Partizip II + worden.', 'grammar_tip': 'Passiv irreal: wäre veröffentlicht worden.'},
])

