"""
Konjunktiv II / Subjunctive Mood — Exercise Bank.

Tests würde+Infinitiv, wenn-clauses with hätte/wäre,
Konjunktiv II Vergangenheit, als ob + Konjunktiv,
and Konjunktiv I (indirect speech).
Exercise types: reconstruction + gap_fill
"""

KONJUNKTIV_BANK = [
    {'id': 'gen_konj_001', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Ich würde mehr reisen, wenn ich genug Geld hätte.', 'verbs': ['würde', 'reisen', 'hätte'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Konjunktiv II mit würde + Infinitiv drückt eine irreale Situation aus; im wenn-Satz steht hätte am Ende.', 'grammar_tip': 'Irreal = würde + Infinitiv, wenn + hätte/wäre.'},
    {'id': 'gen_konj_002', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn ich mehr Zeit hätte, würde ich ein Buch schreiben.', 'verbs': ['hätte', 'würde', 'schreiben'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Im irrealen Bedingungssatz steht hätte im Nebensatz und würde + Infinitiv im Hauptsatz.', 'grammar_tip': 'Wenn + hätte, dann würde.'},
    {'id': 'gen_konj_003', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn er früher käme, wären wir pünktlich.', 'verbs': ['käme', 'wären'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Starke Verben bilden eigene Konjunktiv-II-Formen wie käme und wären.', 'grammar_tip': 'Irreal = Umlaut + -e.'},
    {'id': 'gen_konj_004', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wunsch', 'data': {'text': 'Ich wünschte, ich wäre jetzt am Meer.', 'verbs': ['wünschte', 'wäre'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Wünsche werden mit Konjunktiv II ausgedrückt, oft mit wäre oder hätte.', 'grammar_tip': 'Wunsch = wäre/hätte.'},
    {'id': 'gen_konj_005', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'wuerde_infinitiv', 'data': {'text': 'Er würde dir helfen, wenn du ihn fragen würdest.', 'verbs': ['würde', 'helfen', 'würdest', 'fragen'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'In beiden Teilsätzen steht Konjunktiv II zur Darstellung einer hypothetischen Situation.', 'grammar_tip': 'würde im Hauptsatz, würdest im Nebensatz.'},
    {'id': 'gen_konj_006', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 2, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn ich du wäre, würde ich das Angebot annehmen.', 'verbs': ['wäre', 'würde', 'annehmen'], 'clause_type': 'konjunktiv_wenn'}, 'grammar_rule': 'Bei Ratschlägen steht wäre im wenn-Satz und würde + Infinitiv im Hauptsatz.', 'grammar_tip': 'Wenn ich du wäre ...'},
    {'id': 'gen_konj_007', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Ich hätte dich angerufen, wenn ich deine Nummer gehabt hätte.', 'verbs': ['hätte', 'angerufen', 'gehabt', 'hätte'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Konjunktiv II Vergangenheit wird mit hätte/wäre + Partizip II gebildet.', 'grammar_tip': 'Vergangenheit irreal = hätte + Partizip.'},
    {'id': 'gen_konj_008', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn sie früher gegangen wäre, hätte sie den Zug erreicht.', 'verbs': ['gegangen', 'wäre', 'hätte', 'erreicht'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Im irrealen Vergangenheitssatz stehen wäre oder hätte + Partizip II.', 'grammar_tip': 'wäre gegangen, hätte erreicht.'},
    {'id': 'gen_konj_009', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er tut so, als ob er alles wüsste.', 'verbs': ['tut', 'wüsste'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Nach als ob steht Konjunktiv II zur Beschreibung einer irreale Annahme.', 'grammar_tip': 'Als ob = Konjunktiv II.'},
    {'id': 'gen_konj_010', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Sie spricht, als ob sie Expertin wäre.', 'verbs': ['spricht', 'wäre'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Als-ob-Sätze stehen im Konjunktiv II, da sie eine irreale Vorstellung ausdrücken.', 'grammar_tip': 'Als ob + wäre.'},
    {'id': 'gen_konj_011', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Er hätte mehr gelernt, wenn er nicht so müde gewesen wäre.', 'verbs': ['hätte', 'gelernt', 'gewesen', 'wäre'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Irreale Vergangenheit nutzt hätte/wäre + Partizip II.', 'grammar_tip': 'gewesen wäre.'},
    {'id': 'gen_konj_012', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 3, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Wenn wir früher gestartet wären, hätten wir den Stau vermieden.', 'verbs': ['gestartet', 'wären', 'hätten', 'vermieden'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Beide Teilsätze stehen im Konjunktiv II Vergangenheit.', 'grammar_tip': 'wären gestartet, hätten vermieden.'},
    {'id': 'gen_konj_013', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Er sagte, er {gap_1} krank.', 'gaps': [{'position': 'gap_1', 'context': 'er ___ krank', 'answer': 'sei', 'options': ['ist', 'sei', 'wäre', 'war', 'sein'], 'indicative_hint': 'er ist -> Konjunktiv I?'}], 'full_correct': 'Er sagte, er sei krank.'}, 'grammar_rule': 'Konjunktiv I wird für indirekte Rede verwendet.', 'grammar_tip': 'Indirekte Rede = sei, habe, gehe.'},
    {'id': 'gen_konj_014', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_1', 'data': {'sentence_template': 'Sie meinte, sie {gap_1} keine Zeit.', 'gaps': [{'position': 'gap_1', 'context': 'sie ___ keine Zeit', 'answer': 'habe', 'options': ['hat', 'habe', 'hätte', 'hatte', 'haben'], 'indicative_hint': 'sie hat -> Konjunktiv I?'}], 'full_correct': 'Sie meinte, sie habe keine Zeit.'}, 'grammar_rule': 'In der indirekten Rede steht Konjunktiv I statt Indikativ.', 'grammar_tip': 'habe statt hat.'},
    {'id': 'gen_konj_015', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_2_spezial', 'data': {'sentence_template': 'Wenn er doch nur mehr Mut {gap_1}.', 'gaps': [{'position': 'gap_1', 'context': 'er ___ mehr Mut', 'answer': 'hätte', 'options': ['hat', 'hätte', 'habe', 'hatte', 'haben'], 'indicative_hint': 'er hat -> Wunsch?'}], 'full_correct': 'Wenn er doch nur mehr Mut hätte.'}, 'grammar_rule': 'Konjunktiv II drückt einen unerfüllbaren Wunsch aus.', 'grammar_tip': 'Doch nur + hätte.'},
    {'id': 'gen_konj_016', 'module': 'konjunktiv', 'type': 'gap_fill', 'level': 4, 'topic': 'konjunktiv_2_spezial', 'data': {'sentence_template': 'Er tat, als {gap_1} er alles gewusst.', 'gaps': [{'position': 'gap_1', 'context': 'als ___ er', 'answer': 'hätte', 'options': ['hat', 'habe', 'hätte', 'war', 'sei'], 'indicative_hint': 'Plusquamperfekt?'}], 'full_correct': 'Er tat, als hätte er alles gewusst.'}, 'grammar_rule': 'Als + Konjunktiv II Vergangenheit wird mit hätte + Partizip II gebildet.', 'grammar_tip': 'als hätte er.'},
    {'id': 'gen_konj_017', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_vergangenheit', 'data': {'text': 'Er sagte, er hätte das Projekt beendet, wenn er mehr Unterstützung bekommen hätte.', 'verbs': ['hätte', 'beendet', 'bekommen', 'hätte'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'In komplexen Sätzen stehen mehrere Konjunktiv-II-Formen für irreale Vergangenheit.', 'grammar_tip': 'Mehrfach hätte + Partizip.'},
    {'id': 'gen_konj_018', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'als_ob_konjunktiv', 'data': {'text': 'Er verhielt sich, als ob er nichts bemerkt hätte.', 'verbs': ['verhielt', 'hätte', 'bemerkt'], 'clause_type': 'als_ob_konjunktiv'}, 'grammar_rule': 'Als-ob-Sätze im Konjunktiv II Vergangenheit drücken Irrealität aus.', 'grammar_tip': 'als ob + hätte + Partizip.'},
    {'id': 'gen_konj_019', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'wunsch', 'data': {'text': 'Hätte ich doch nur besser aufgepasst, wäre das nicht passiert.', 'verbs': ['Hätte', 'aufgepasst', 'wäre', 'passiert'], 'clause_type': 'wunsch'}, 'grammar_rule': 'Inversion mit hätte am Satzanfang drückt einen unerfüllten Wunsch aus.', 'grammar_tip': 'Hätte ich doch ...'},
    {'id': 'gen_konj_020', 'module': 'konjunktiv', 'type': 'reconstruction', 'level': 4, 'topic': 'konjunktiv_wenn', 'data': {'text': 'Wenn er nicht so spät gekommen wäre, hätte er den Vortrag noch hören können.', 'verbs': ['gekommen', 'wäre', 'hätte', 'hören', 'können'], 'clause_type': 'konjunktiv_vergangenheit'}, 'grammar_rule': 'Komplexer irrealer Bedingungssatz mit Konjunktiv II Vergangenheit im Nebensatz und Hauptsatz.', 'grammar_tip': 'wäre gekommen, hätte hören können.'},
]

