"""
Connectors & Word Order (Konnektoren & Satzstellung) — Exercise Bank.

Tests hauptsatz connectors, nebensatz connectors, adverbial connectors,
two-part connectors, and complex multi-clause sentences.
Exercise type: reconstruction
"""

KONNEKTOREN_BANK = [
    # ===== EXISTING (now with English translations added) =====
    {'id': 'gen_kon_001', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich wollte ins Kino gehen, aber ich hatte keine Zeit.',
              'english': 'I wanted to go to the cinema, but I didn’t have time.',
              'verbs': ['wollte', 'hatte'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': 'Hauptsatz-Konnektoren wie „aber“ verbinden zwei Hauptsätze; nach dem Konnektor bleibt die normale Wortstellung (Subjekt + Verb).',
     'grammar_tip': 'Aber, und, oder, denn = kein Verb am Ende, keine Inversion.'},

    {'id': 'gen_kon_002', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Er lernt viel, denn er schreibt morgen eine Prüfung.',
              'english': 'He studies a lot, because he has an exam tomorrow.',
              'verbs': ['lernt', 'schreibt'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Denn“ verbindet zwei Hauptsätze; im zweiten Satz steht das Verb wie im normalen Hauptsatz an Position 2.',
     'grammar_tip': 'Denn = Hauptsatz + Hauptsatz.'},

    {'id': 'gen_kon_003', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Sie trinkt keinen Kaffee, sondern sie bestellt einen Tee.',
              'english': 'She doesn’t drink coffee, but instead she orders tea.',
              'verbs': ['trinkt', 'bestellt'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Sondern“ verbindet zwei Hauptsätze nach einer Verneinung; die Wortstellung bleibt Subjekt + Verb.',
     'grammar_tip': 'Sondern folgt auf eine Verneinung und ändert die Wortstellung nicht.'},

    {'id': 'gen_kon_004', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Wir fahren ans Meer, oder wir bleiben zu Hause.',
              'english': 'We’re going to the sea, or we’re staying at home.',
              'verbs': ['fahren', 'bleiben'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Oder“ verbindet gleichwertige Hauptsätze; beide behalten die normale Verbzweitstellung.',
     'grammar_tip': 'Oder = normale Hauptsatzstellung.'},

    {'id': 'gen_kon_005', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Er kocht das Abendessen, und sie deckt den Tisch.',
              'english': 'He cooks dinner, and she sets the table.',
              'verbs': ['kocht', 'deckt'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Und“ verbindet zwei Hauptsätze ohne Veränderung der Wortstellung.',
     'grammar_tip': 'Und = zwei Hauptsätze, beide mit Verb an Position 2.'},

    {'id': 'gen_kon_006', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Ich bleibe zu Hause, weil ich krank bin.',
              'english': 'I’m staying at home because I’m sick.',
              'verbs': ['bleibe', 'bin'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': 'Nach „weil“ steht das konjugierte Verb im Nebensatz am Ende.',
     'grammar_tip': 'Weil = Verb ganz am Ende.'},

    {'id': 'gen_kon_007', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Sie sagt, dass sie morgen früher kommt.',
              'english': 'She says that she will come earlier tomorrow.',
              'verbs': ['sagt', 'kommt'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Dass“ leitet einen Nebensatz ein; das Verb steht am Satzende.',
     'grammar_tip': 'Dass-Satz = Verb am Schluss.'},

    {'id': 'gen_kon_008', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor',
     'data': {'text': 'Es regnet stark, deshalb bleiben wir zu Hause.',
              'english': 'It’s raining heavily, so we’re staying at home.',
              'verbs': ['regnet', 'bleiben'], 'clause_type': 'deshalb_inversion'},
     'grammar_rule': '„Deshalb“ ist ein Adverb; es steht auf Position 1, das Verb folgt direkt danach (Inversion).',
     'grammar_tip': 'Deshalb = Verb direkt nach dem Konnektor.'},

    {'id': 'gen_kon_009', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor',
     'data': {'text': 'Er war müde, trotzdem ging er noch joggen.',
              'english': 'He was tired, yet he still went jogging.',
              'verbs': ['war', 'ging'], 'clause_type': 'deshalb_inversion'},
     'grammar_rule': 'Nach „trotzdem“ steht das Verb vor dem Subjekt, da es ein Satzadverb ist.',
     'grammar_tip': 'Trotzdem = Verb vor Subjekt.'},

    {'id': 'gen_kon_010', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Obwohl er wenig Zeit hat, hilft er seinen Kollegen.',
              'english': 'Although he has little time, he helps his colleagues.',
              'verbs': ['hat', 'hilft'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Obwohl“ leitet einen Nebensatz ein; das Verb steht am Ende des Nebensatzes.',
     'grammar_tip': 'Obwohl = Nebensatz mit Verb am Ende.'},

    {'id': 'gen_kon_011', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Entweder gehen wir heute ins Theater, oder wir bleiben zu Hause.',
              'english': 'Either we go to the theatre today, or we stay at home.',
              'verbs': ['gehen', 'bleiben'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Entweder ... oder“ verbindet zwei Hauptsätze; beide behalten die Verbzweitstellung.',
     'grammar_tip': 'Zweiteilig, aber beide Teile sind Hauptsätze.'},

    {'id': 'gen_kon_012', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Sowohl der Chef als auch die Mitarbeiter unterstützen das Projekt.',
              'english': 'Both the boss and the employees support the project.',
              'verbs': ['unterstützen'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Sowohl ... als auch“ verbindet Satzteile; das Verb richtet sich nach dem pluralischen Subjekt.',
     'grammar_tip': 'Sowohl ... als auch = ein gemeinsames Verb.'},

    {'id': 'gen_kon_013', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Je mehr du lernst, desto besser verstehst du den Stoff.',
              'english': 'The more you study, the better you understand the material.',
              'verbs': ['lernst', 'verstehst'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Je ... desto“ bildet zwei Teilsätze; beide haben Verbzweitstellung.',
     'grammar_tip': 'Je-Satz zuerst, desto-Satz mit Verb an Position 2.'},

    {'id': 'gen_kon_014', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Nicht nur er spricht drei Sprachen, sondern auch seine Schwester reist viel.',
              'english': 'Not only does he speak three languages, but his sister also travels a lot.',
              'verbs': ['spricht', 'reist'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Nicht nur ... sondern auch“ verbindet zwei Hauptsätze mit normaler Wortstellung.',
     'grammar_tip': 'Beide Teile bleiben Hauptsätze.'},

    {'id': 'gen_kon_015', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Zwar ist das Hotel teuer, aber es bietet einen tollen Service.',
              'english': 'The hotel is expensive, but it offers great service.',
              'verbs': ['ist', 'bietet'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Zwar ... aber“ verbindet zwei Hauptsätze; beide behalten die Verbzweitstellung.',
     'grammar_tip': 'Zwar im ersten, aber im zweiten – beide mit Verb an Position 2.'},

    {'id': 'gen_kon_016', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Obwohl er müde war, ist er zur Arbeit gegangen, weil er einen wichtigen Termin hatte.',
              'english': 'Although he was tired, he went to work because he had an important appointment.',
              'verbs': ['war', 'ist', 'gegangen', 'hatte'], 'clause_type': 'complex_mixed'},
     'grammar_rule': 'Nebensätze mit „obwohl“ und „weil“ haben das Verb am Ende; der Hauptsatz behält Verbzweitstellung.',
     'grammar_tip': 'Nebensatz = Verb am Ende, Hauptsatz = Verb an Position 2.'},

    {'id': 'gen_kon_017', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Er sagt, dass er kommen wird, obwohl er eigentlich keine Zeit hat.',
              'english': 'He says that he will come, although he actually has no time.',
              'verbs': ['sagt', 'kommen', 'wird', 'hat'], 'clause_type': 'complex_mixed'},
     'grammar_rule': 'Im dass- und obwohl-Satz steht das konjugierte Verb am Ende; im Hauptsatz bleibt die Verbzweitstellung.',
     'grammar_tip': 'Mehrere Nebensätze = jedes Verb ans jeweilige Ende.'},

    {'id': 'gen_kon_018', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Es regnete stark, deshalb mussten wir warten, bis der Zug ankam.',
              'english': 'It rained heavily, so we had to wait until the train arrived.',
              'verbs': ['regnete', 'mussten', 'warten', 'ankam'], 'clause_type': 'complex_mixed'},
     'grammar_rule': 'Nach „deshalb“ folgt Inversion; im „bis“-Nebensatz steht das Verb am Ende.',
     'grammar_tip': 'Adverb + Inversion, Nebensatz + Verb am Ende.'},

    {'id': 'gen_kon_019', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Wenn du früher kommst, können wir anfangen, obwohl noch nicht alle da sind.',
              'english': 'If you come earlier, we can start, although not everyone is there yet.',
              'verbs': ['kommst', 'können', 'anfangen', 'sind'], 'clause_type': 'complex_mixed'},
     'grammar_rule': 'Im wenn- und obwohl-Satz steht das Verb am Ende; der Hauptsatz bleibt mit Verb an Position 2.',
     'grammar_tip': 'Jeder Nebensatz hat sein eigenes Verb am Schluss.'},

    {'id': 'gen_kon_020', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Er arbeitet viel, dennoch findet er Zeit für seine Familie, weil sie ihm wichtig ist.',
              'english': 'He works a lot; nevertheless, he finds time for his family because they are important to him.',
              'verbs': ['arbeitet', 'findet', 'ist'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„Dennoch“ führt zur Inversion im Hauptsatz; im weil-Satz steht das Verb am Ende.',
     'grammar_tip': 'Adverb + Inversion, weil + Verb ans Ende.'},

    # ===== NEW: Level 1 (10) — Hauptsatz-Konnektoren (aber/denn/sondern/oder/und) =====
    {'id': 'gen_kon_021', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich wollte nach der Arbeit Deutsch lernen, aber ich war zu müde.',
              'english': 'I wanted to study German after work, but I was too tired.',
              'verbs': ['wollte', 'war'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Aber“ verbindet zwei Hauptsätze; nach „aber“ bleibt die normale Hauptsatzstellung.',
     'grammar_tip': 'Aber = kein Verb am Ende, keine Inversion.'},

    {'id': 'gen_kon_022', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich trinke heute keinen Kaffee, sondern ich bestelle einen Tee.',
              'english': 'I’m not drinking coffee today; instead I’m ordering a tea.',
              'verbs': ['trinke', 'bestelle'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Sondern“ folgt auf eine Verneinung und verbindet zwei Hauptsätze ohne Wortstellungsänderung.',
     'grammar_tip': 'Nicht X, sondern Y.'},

    {'id': 'gen_kon_023', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich bleibe heute länger im Büro, denn ich habe noch ein Meeting.',
              'english': 'I’m staying longer in the office today because I still have a meeting.',
              'verbs': ['bleibe', 'habe'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Denn“ verbindet zwei Hauptsätze; der zweite Satz bleibt ein normaler Hauptsatz.',
     'grammar_tip': 'Denn = Hauptsatz + Hauptsatz.'},

    {'id': 'gen_kon_024', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Wir kochen heute zu Hause, oder wir gehen schnell etwas essen.',
              'english': 'We’ll cook at home today, or we’ll quickly go out to eat something.',
              'verbs': ['kochen', 'gehen'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Oder“ verbindet zwei gleichwertige Hauptsätze; beide haben Verbzweitstellung.',
     'grammar_tip': 'Oder = normale Hauptsatzstellung.'},

    {'id': 'gen_kon_025', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich öffne Bloomberg, und ich prüfe die Kurse.',
              'english': 'I open Bloomberg, and I check the prices.',
              'verbs': ['öffne', 'prüfe'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Und“ verbindet zwei Hauptsätze; die Wortstellung bleibt unverändert.',
     'grammar_tip': 'Und = zwei Hauptsätze, beide mit Verb an Position 2.'},

    {'id': 'gen_kon_026', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich wollte am Wochenende verreisen, aber das Wetter war schlecht.',
              'english': 'I wanted to travel on the weekend, but the weather was bad.',
              'verbs': ['wollte', 'war'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Aber“ verbindet zwei Hauptsätze; danach bleibt die Hauptsatz-Wortstellung.',
     'grammar_tip': 'Aber = kein Verb am Ende.'},

    {'id': 'gen_kon_027', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich arbeite nicht im Homeoffice, sondern ich fahre ins Büro.',
              'english': 'I’m not working from home; instead I’m going to the office.',
              'verbs': ['arbeite', 'fahre'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Sondern“ korrigiert nach einer Verneinung; beide Sätze sind Hauptsätze.',
     'grammar_tip': 'Sondern folgt auf „nicht/kein“.'},

    {'id': 'gen_kon_028', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich gehe heute früher schlafen, denn morgen beginnt der Tag früh.',
              'english': 'I’m going to sleep earlier today because tomorrow the day starts early.',
              'verbs': ['gehe', 'beginnt'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Denn“ = Hauptsatz-Konnektor; keine Inversion und kein Verb am Ende.',
     'grammar_tip': 'Denn ist wie „weil“, aber mit Hauptsatzstellung.'},

    {'id': 'gen_kon_029', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Wir gehen ins Fitnessstudio, oder wir machen einen Spaziergang am Main.',
              'english': 'We’ll go to the gym, or we’ll take a walk by the Main river.',
              'verbs': ['gehen', 'machen'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Oder“ verbindet Alternativen; beide Teile bleiben Hauptsätze.',
     'grammar_tip': 'Oder = Verb an Position 2.'},

    {'id': 'gen_kon_030', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor',
     'data': {'text': 'Ich koche eine Suppe, und ich höre dabei einen Podcast.',
              'english': 'I cook a soup, and I listen to a podcast while doing it.',
              'verbs': ['koche', 'höre'], 'clause_type': 'aber_hauptsatz'},
     'grammar_rule': '„Und“ verbindet zwei Hauptsätze ohne Wortstellungsänderung.',
     'grammar_tip': 'Und = normaler Hauptsatz.'},

    # ===== NEW: Level 2 (10) — Nebensatz (weil/dass/obwohl) + Adverb (deshalb/trotzdem) =====
    {'id': 'gen_kon_031', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Ich bleibe heute länger im Büro, weil ich einen Bericht fertig machen muss.',
              'english': 'I’m staying longer in the office today because I have to finish a report.',
              'verbs': ['bleibe', 'muss'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Weil“ leitet einen Nebensatz ein; das konjugierte Verb steht am Ende.',
     'grammar_tip': 'Weil = Verb am Ende.'},

    {'id': 'gen_kon_032', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Mein Kollege sagt, dass wir die Zahlen noch einmal prüfen sollen.',
              'english': 'My colleague says that we should check the numbers once again.',
              'verbs': ['sagt', 'sollen'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Dass“ startet einen Nebensatz; das konjugierte Verb steht am Ende.',
     'grammar_tip': 'Dass-Satz = Verb am Schluss.'},

    {'id': 'gen_kon_033', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor',
     'data': {'text': 'Der Zug hatte Verspätung, deshalb kam ich zu spät ins Meeting.',
              'english': 'The train was delayed, so I arrived late to the meeting.',
              'verbs': ['hatte', 'kam'], 'clause_type': 'deshalb_inversion'},
     'grammar_rule': '„Deshalb“ steht oft auf Position 1; danach kommt das Verb (Inversion).',
     'grammar_tip': 'Deshalb = Verb direkt danach.'},

    {'id': 'gen_kon_034', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor',
     'data': {'text': 'Ich war müde, trotzdem habe ich noch 20 Minuten Deutsch geübt.',
              'english': 'I was tired, yet I still practised German for 20 minutes.',
              'verbs': ['war', 'habe', 'geübt'], 'clause_type': 'deshalb_inversion'},
     'grammar_rule': '„Trotzdem“ ist ein Satzadverb; es löst häufig Inversion aus.',
     'grammar_tip': 'Trotzdem = Verb vor Subjekt.'},

    {'id': 'gen_kon_035', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Obwohl ich wenig Zeit habe, lese ich jeden Tag kurze Artikel auf Deutsch.',
              'english': 'Although I have little time, I read short articles in German every day.',
              'verbs': ['habe', 'lese'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Obwohl“ leitet einen Nebensatz ein; das Verb steht am Ende des Nebensatzes.',
     'grammar_tip': 'Obwohl = Verb am Ende.'},

    {'id': 'gen_kon_036', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Ich gehe heute nicht laufen, weil es draußen zu kalt ist.',
              'english': 'I’m not going running today because it’s too cold outside.',
              'verbs': ['gehe', 'ist'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': 'Nach „weil“ steht das konjugierte Verb am Ende des Nebensatzes.',
     'grammar_tip': 'Weil = Verb am Ende.'},

    {'id': 'gen_kon_037', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Ich hoffe, dass ich bald flüssiger sprechen kann.',
              'english': 'I hope that I can speak more fluently soon.',
              'verbs': ['hoffe', 'kann'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Dass“ leitet einen Nebensatz ein; das konjugierte Verb steht am Ende.',
     'grammar_tip': 'Dass = Verb am Schluss.'},

    {'id': 'gen_kon_038', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor',
     'data': {'text': 'Ich musste früh aufstehen, deshalb bin ich heute Abend schneller müde.',
              'english': 'I had to get up early, so I’m tired faster this evening.',
              'verbs': ['musste', 'bin'], 'clause_type': 'deshalb_inversion'},
     'grammar_rule': '„Deshalb“ auf Position 1 → Verb direkt danach (Inversion).',
     'grammar_tip': 'Deshalb = Verb vor Subjekt.'},

    {'id': 'gen_kon_039', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor',
     'data': {'text': 'Der Tag war stressig, trotzdem habe ich noch gekocht.',
              'english': 'The day was stressful, yet I still cooked.',
              'verbs': ['war', 'habe', 'gekocht'], 'clause_type': 'deshalb_inversion'},
     'grammar_rule': '„Trotzdem“ führt oft zu Inversion: Verb steht vor dem Subjekt.',
     'grammar_tip': 'Trotzdem = Verb direkt danach.'},

    {'id': 'gen_kon_040', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor',
     'data': {'text': 'Obwohl das Restaurant voll war, haben wir noch einen Tisch bekommen.',
              'english': 'Although the restaurant was full, we still got a table.',
              'verbs': ['war', 'haben', 'bekommen'], 'clause_type': 'weil_nebensatz'},
     'grammar_rule': '„Obwohl“ → Nebensatz; Verb am Ende des Nebensatzes.',
     'grammar_tip': 'Obwohl = Verb am Ende.'},

    # ===== NEW: Level 3 (10) — zweiteilige Konnektoren =====
    {'id': 'gen_kon_041', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Entweder fahre ich am Freitag nach Hause, oder ich bleibe in der Stadt.',
              'english': 'Either I travel home on Friday, or I stay in the city.',
              'verbs': ['fahre', 'bleibe'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Entweder ... oder“ verbindet zwei Hauptsätze; beide bleiben Verbzweit.',
     'grammar_tip': 'Beide Teile = Hauptsatz.'},

    {'id': 'gen_kon_042', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Entweder koche ich zu Hause, oder ich hole mir etwas Schnelles nach der Arbeit.',
              'english': 'Either I cook at home, or I grab something quick after work.',
              'verbs': ['koche', 'hole'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Entweder ... oder“ = zwei Hauptsätze mit normaler Verbzweitstellung.',
     'grammar_tip': 'Oder-Teil ist auch Hauptsatz.'},

    {'id': 'gen_kon_043', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Sowohl mein Team als auch ich arbeiten gerade an einem neuen Modell.',
              'english': 'Both my team and I are currently working on a new model.',
              'verbs': ['arbeiten'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Sowohl ... als auch“ verbindet Satzteile; das Verb steht im Plural.',
     'grammar_tip': 'Sowohl + als auch = pluralisches Subjekt.'},

    {'id': 'gen_kon_044', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Sowohl am Morgen als auch am Abend übe ich ein bisschen Deutsch.',
              'english': 'I practise a bit of German both in the morning and in the evening.',
              'verbs': ['übe'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Sowohl ... als auch“ kann auch Adverbialteile verbinden; der Satz bleibt ein Hauptsatz.',
     'grammar_tip': 'Ein Satz, ein Verb.'},

    {'id': 'gen_kon_045', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Je mehr ich auf Deutsch lese, desto schneller erkenne ich typische Formulierungen.',
              'english': 'The more I read in German, the faster I recognise typical phrasing.',
              'verbs': ['lese', 'erkenne'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Je ... desto“ bildet zwei Teilsätze; beide mit Verbzweitstellung.',
     'grammar_tip': 'Je-Satz zuerst, desto-Satz auch Verbzweit.'},

    {'id': 'gen_kon_046', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Je besser ich die Konnektoren kann, desto klarer klingen meine E-Mails.',
              'english': 'The better I know connectors, the clearer my emails sound.',
              'verbs': ['kann', 'klingen'], 'clause_type': 'zweiteilig'},
     'grammar_rule': 'Bei „je ... desto“ bleiben beide Teilsätze Verbzweit.',
     'grammar_tip': 'Je ... desto = Vergleich/Steigerung.'},

    {'id': 'gen_kon_047', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Nicht nur ich lerne Deutsch, sondern auch meine Kollegen üben manchmal.',
              'english': 'Not only do I learn German, but my colleagues also practise sometimes.',
              'verbs': ['lerne', 'üben'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Nicht nur ... sondern auch“ verbindet zwei Hauptsätze; normale Verbzweitstellung.',
     'grammar_tip': 'Beide Teile = Hauptsatz.'},

    {'id': 'gen_kon_048', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Nicht nur das Tempo ist hoch, sondern auch die Verantwortung ist groß.',
              'english': 'Not only is the pace high, but the responsibility is also big.',
              'verbs': ['ist', 'ist'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Nicht nur ... sondern auch“: zwei Hauptsätze mit Verbzweitstellung.',
     'grammar_tip': 'Verb bleibt an Position 2.'},

    {'id': 'gen_kon_049', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Zwar ist mein Deutsch noch nicht perfekt, aber ich werde jeden Tag besser.',
              'english': 'My German isn’t perfect yet, but I’m getting better every day.',
              'verbs': ['ist', 'werde'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Zwar ... aber“ verbindet zwei Hauptsätze; beide bleiben Verbzweit.',
     'grammar_tip': 'Zwar im ersten, aber im zweiten.'},

    {'id': 'gen_kon_050', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor',
     'data': {'text': 'Zwar kostet der Deutschkurs Zeit, aber er hilft mir im Alltag sehr.',
              'english': 'The German course takes time, but it helps me a lot in everyday life.',
              'verbs': ['kostet', 'hilft'], 'clause_type': 'zweiteilig'},
     'grammar_rule': '„Zwar ... aber“ = zwei Hauptsätze, beide Verbzweit.',
     'grammar_tip': 'Keine Verb-Endstellung.'},

    # ===== NEW: Level 4 (10) — komplex gemischt (Nebensätze + Adverbien + mehrere Konnektoren) =====
    {'id': 'gen_kon_051', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Obwohl der Markt heute ruhig war, hatte ich viel zu tun, weil wir ein neues Modell getestet haben.',
              'english': 'Although the market was calm today, I had a lot to do because we tested a new model.',
              'verbs': ['war', 'hatte', 'getestet', 'haben'], 'clause_type': 'complex_mixed'},
     'grammar_rule': 'Nebensätze mit „obwohl/weil“ → Verb am Ende; Hauptsatz → Verbzweit.',
     'grammar_tip': 'Jeder Nebensatz: Verb ans Ende.'},

    {'id': 'gen_kon_052', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Ich habe früher Feierabend gemacht, deshalb konnte ich kochen, obwohl ich eigentlich müde war.',
              'english': 'I finished work earlier, so I could cook, although I was actually tired.',
              'verbs': ['habe', 'gemacht', 'konnte', 'kochen', 'war'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„Deshalb“ → Inversion im Hauptsatz; „obwohl“ → Nebensatz mit Verb am Ende.',
     'grammar_tip': 'Deshalb: Verb direkt danach. Obwohl: Verb am Ende.'},

    {'id': 'gen_kon_053', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Ich hoffe, dass ich bald flüssiger spreche, obwohl ich manchmal Angst habe, Fehler zu machen.',
              'english': 'I hope that I’ll speak more fluently soon, although I’m sometimes afraid of making mistakes.',
              'verbs': ['hoffe', 'spreche', 'habe', 'machen'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„dass/obwohl“ leiten Nebensätze ein; das konjugierte Verb steht jeweils am Ende.',
     'grammar_tip': 'Mehrere Nebensätze = mehrere Verb-Endstellungen.'},

    {'id': 'gen_kon_054', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Wenn ich morgens pendle, höre ich einen Podcast, damit ich die Zeit nutze, obwohl es oft laut ist.',
              'english': 'When I commute in the morning, I listen to a podcast so that I use the time, although it’s often loud.',
              'verbs': ['pendle', 'höre', 'nutze', 'ist'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„wenn/damit/obwohl“ = Nebensätze mit Verb am Ende; Hauptsatz bleibt Verbzweit.',
     'grammar_tip': 'Jeder Nebensatz: Verb am Schluss.'},

    {'id': 'gen_kon_055', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Der Termin wurde verschoben, deshalb musste ich umplanen, weil ich danach noch einen Kurs habe.',
              'english': 'The appointment was postponed, so I had to reschedule because I have a class afterwards.',
              'verbs': ['wurde', 'verschoben', 'musste', 'umplanen', 'habe'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„Deshalb“ erzeugt Inversion; „weil“ leitet einen Nebensatz mit Verb am Ende ein.',
     'grammar_tip': 'Deshalb: Verb vor Subjekt. Weil: Verb ans Ende.'},

    {'id': 'gen_kon_056', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Obwohl ich wenig Zeit hatte, habe ich die Übung gemacht, weil ich konsequent bleiben will.',
              'english': 'Although I had little time, I did the exercise because I want to stay consistent.',
              'verbs': ['hatte', 'habe', 'gemacht', 'will', 'bleiben'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„obwohl/weil“ = Nebensatz, Verb am Ende; Hauptsatz bleibt Verbzweit.',
     'grammar_tip': 'Zwei Nebensätze = zwei Verb-Enden.'},

    {'id': 'gen_kon_057', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Ich habe das Rezept geändert, trotzdem hat es gut geschmeckt, obwohl ich weniger Zutaten hatte.',
              'english': 'I changed the recipe; nevertheless it tasted good, although I had fewer ingredients.',
              'verbs': ['habe', 'geändert', 'hat', 'geschmeckt', 'hatte'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„trotzdem“ → Inversion im Hauptsatz; „obwohl“ → Nebensatz mit Verb am Ende.',
     'grammar_tip': 'Trotzdem: Verb direkt danach. Obwohl: Verb ans Ende.'},

    {'id': 'gen_kon_058', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Ich habe gemerkt, dass ich schneller lerne, wenn ich viel lese, deshalb mache ich das jetzt täglich.',
              'english': 'I noticed that I learn faster when I read a lot, so I do that daily now.',
              'verbs': ['habe', 'gemerkt', 'lerne', 'lese', 'mache'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„dass/wenn“ → Nebensatz mit Verb am Ende; „deshalb“ → Inversion im Hauptsatz.',
     'grammar_tip': 'Nebensatz: Verb ans Ende. Deshalb: Verb direkt danach.'},

    {'id': 'gen_kon_059', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Obwohl der Tag lang war, bin ich noch spazieren gegangen, weil mir Bewegung guttut.',
              'english': 'Although the day was long, I still went for a walk because movement does me good.',
              'verbs': ['war', 'bin', 'gegangen', 'guttut'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„obwohl/weil“ = Nebensätze mit Verb am Ende; Hauptsatz bleibt Verbzweit.',
     'grammar_tip': 'Nebensatz Ende, Hauptsatz V2.'},

    {'id': 'gen_kon_060', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren',
     'data': {'text': 'Der Bus kam zu spät, deshalb habe ich den Kurs verpasst, obwohl ich extra früher losgegangen bin.',
              'english': 'The bus came too late, so I missed the class, although I left extra early.',
              'verbs': ['kam', 'habe', 'verpasst', 'bin', 'losgegangen'], 'clause_type': 'complex_mixed'},
     'grammar_rule': '„deshalb“ → Inversion; „obwohl“ → Nebensatz mit Verb am Ende.',
     'grammar_tip': 'Deshalb: Verb direkt nach dem Adverb. Obwohl: Verb ans Ende.'},
]

