"""
Connectors & Word Order (Konnektoren & Satzstellung) — Exercise Bank.

Tests hauptsatz connectors, nebensatz connectors, adverbial connectors,
two-part connectors, and complex multi-clause sentences.
Exercise type: reconstruction
"""

KONNEKTOREN_BANK = [
    {'id': 'gen_kon_001', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor', 'data': {'text': 'Ich wollte ins Kino gehen, aber ich hatte keine Zeit.', 'verbs': ['wollte', 'hatte'], 'clause_type': 'aber_hauptsatz'}, 'grammar_rule': 'Hauptsatz-Konnektoren wie „aber“ verbinden zwei Hauptsätze; nach dem Konnektor bleibt die normale Wortstellung (Subjekt + Verb).', 'grammar_tip': 'Aber, und, oder, denn = kein Verb am Ende, keine Inversion.'},
    {'id': 'gen_kon_002', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor', 'data': {'text': 'Er lernt viel, denn er schreibt morgen eine Prüfung.', 'verbs': ['lernt', 'schreibt'], 'clause_type': 'aber_hauptsatz'}, 'grammar_rule': '„Denn“ verbindet zwei Hauptsätze; im zweiten Satz steht das Verb wie im normalen Hauptsatz an Position 2.', 'grammar_tip': 'Denn = Hauptsatz + Hauptsatz.'},
    {'id': 'gen_kon_003', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor', 'data': {'text': 'Sie trinkt keinen Kaffee, sondern sie bestellt einen Tee.', 'verbs': ['trinkt', 'bestellt'], 'clause_type': 'aber_hauptsatz'}, 'grammar_rule': '„Sondern“ verbindet zwei Hauptsätze nach einer Verneinung; die Wortstellung bleibt Subjekt + Verb.', 'grammar_tip': 'Sondern folgt auf eine Verneinung und ändert die Wortstellung nicht.'},
    {'id': 'gen_kon_004', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor', 'data': {'text': 'Wir fahren ans Meer, oder wir bleiben zu Hause.', 'verbs': ['fahren', 'bleiben'], 'clause_type': 'aber_hauptsatz'}, 'grammar_rule': '„Oder“ verbindet gleichwertige Hauptsätze; beide behalten die normale Verbzweitstellung.', 'grammar_tip': 'Oder = normale Hauptsatzstellung.'},
    {'id': 'gen_kon_005', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 1, 'topic': 'hauptsatz_konnektor', 'data': {'text': 'Er kocht das Abendessen, und sie deckt den Tisch.', 'verbs': ['kocht', 'deckt'], 'clause_type': 'aber_hauptsatz'}, 'grammar_rule': '„Und“ verbindet zwei Hauptsätze ohne Veränderung der Wortstellung.', 'grammar_tip': 'Und = zwei Hauptsätze, beide mit Verb an Position 2.'},
    {'id': 'gen_kon_006', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor', 'data': {'text': 'Ich bleibe zu Hause, weil ich krank bin.', 'verbs': ['bleibe', 'bin'], 'clause_type': 'weil_nebensatz'}, 'grammar_rule': 'Nach „weil“ steht das konjugierte Verb im Nebensatz am Ende.', 'grammar_tip': 'Weil = Verb ganz am Ende.'},
    {'id': 'gen_kon_007', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor', 'data': {'text': 'Sie sagt, dass sie morgen früher kommt.', 'verbs': ['sagt', 'kommt'], 'clause_type': 'weil_nebensatz'}, 'grammar_rule': '„Dass“ leitet einen Nebensatz ein; das Verb steht am Satzende.', 'grammar_tip': 'Dass-Satz = Verb am Schluss.'},
    {'id': 'gen_kon_008', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor', 'data': {'text': 'Es regnet stark, deshalb bleiben wir zu Hause.', 'verbs': ['regnet', 'bleiben'], 'clause_type': 'deshalb_inversion'}, 'grammar_rule': '„Deshalb“ ist ein Adverb; es steht auf Position 1, das Verb folgt direkt danach (Inversion).', 'grammar_tip': 'Deshalb = Verb direkt nach dem Konnektor.'},
    {'id': 'gen_kon_009', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'adverbial_konnektor', 'data': {'text': 'Er war müde, trotzdem ging er noch joggen.', 'verbs': ['war', 'ging'], 'clause_type': 'deshalb_inversion'}, 'grammar_rule': 'Nach „trotzdem“ steht das Verb vor dem Subjekt, da es ein Satzadverb ist.', 'grammar_tip': 'Trotzdem = Verb vor Subjekt.'},
    {'id': 'gen_kon_010', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 2, 'topic': 'nebensatz_konnektor', 'data': {'text': 'Obwohl er wenig Zeit hat, hilft er seinen Kollegen.', 'verbs': ['hat', 'hilft'], 'clause_type': 'weil_nebensatz'}, 'grammar_rule': '„Obwohl“ leitet einen Nebensatz ein; das Verb steht am Ende des Nebensatzes.', 'grammar_tip': 'Obwohl = Nebensatz mit Verb am Ende.'},
    {'id': 'gen_kon_011', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor', 'data': {'text': 'Entweder gehen wir heute ins Theater, oder wir bleiben zu Hause.', 'verbs': ['gehen', 'bleiben'], 'clause_type': 'zweiteilig'}, 'grammar_rule': '„Entweder ... oder“ verbindet zwei Hauptsätze; beide behalten die Verbzweitstellung.', 'grammar_tip': 'Zweiteilig, aber beide Teile sind Hauptsätze.'},
    {'id': 'gen_kon_012', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor', 'data': {'text': 'Sowohl der Chef als auch die Mitarbeiter unterstützen das Projekt.', 'verbs': ['unterstützen'], 'clause_type': 'zweiteilig'}, 'grammar_rule': '„Sowohl ... als auch“ verbindet Satzteile; das Verb richtet sich nach dem pluralischen Subjekt.', 'grammar_tip': 'Sowohl ... als auch = ein gemeinsames Verb.'},
    {'id': 'gen_kon_013', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor', 'data': {'text': 'Je mehr du lernst, desto besser verstehst du den Stoff.', 'verbs': ['lernst', 'verstehst'], 'clause_type': 'zweiteilig'}, 'grammar_rule': '„Je ... desto“ bildet zwei Teilsätze; beide haben Verbzweitstellung.', 'grammar_tip': 'Je-Satz zuerst, desto-Satz mit Verb an Position 2.'},
    {'id': 'gen_kon_014', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor', 'data': {'text': 'Nicht nur er spricht drei Sprachen, sondern auch seine Schwester reist viel.', 'verbs': ['spricht', 'reist'], 'clause_type': 'zweiteilig'}, 'grammar_rule': '„Nicht nur ... sondern auch“ verbindet zwei Hauptsätze mit normaler Wortstellung.', 'grammar_tip': 'Beide Teile bleiben Hauptsätze.'},
    {'id': 'gen_kon_015', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 3, 'topic': 'zweiteilig_konnektor', 'data': {'text': 'Zwar ist das Hotel teuer, aber es bietet einen tollen Service.', 'verbs': ['ist', 'bietet'], 'clause_type': 'zweiteilig'}, 'grammar_rule': '„Zwar ... aber“ verbindet zwei Hauptsätze; beide behalten die Verbzweitstellung.', 'grammar_tip': 'Zwar im ersten, aber im zweiten – beide mit Verb an Position 2.'},
    {'id': 'gen_kon_016', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren', 'data': {'text': 'Obwohl er müde war, ist er zur Arbeit gegangen, weil er einen wichtigen Termin hatte.', 'verbs': ['war', 'ist', 'gegangen', 'hatte'], 'clause_type': 'complex_mixed'}, 'grammar_rule': 'Nebensätze mit „obwohl“ und „weil“ haben das Verb am Ende; der Hauptsatz behält Verbzweitstellung.', 'grammar_tip': 'Nebensatz = Verb am Ende, Hauptsatz = Verb an Position 2.'},
    {'id': 'gen_kon_017', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren', 'data': {'text': 'Er sagt, dass er kommen wird, obwohl er eigentlich keine Zeit hat.', 'verbs': ['sagt', 'kommen', 'wird', 'hat'], 'clause_type': 'complex_mixed'}, 'grammar_rule': 'Im dass- und obwohl-Satz steht das konjugierte Verb am Ende; im Hauptsatz bleibt die Verbzweitstellung.', 'grammar_tip': 'Mehrere Nebensätze = jedes Verb ans jeweilige Ende.'},
    {'id': 'gen_kon_018', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren', 'data': {'text': 'Es regnete stark, deshalb mussten wir warten, bis der Zug ankam.', 'verbs': ['regnete', 'mussten', 'warten', 'ankam'], 'clause_type': 'complex_mixed'}, 'grammar_rule': 'Nach „deshalb“ folgt Inversion; im „bis“-Nebensatz steht das Verb am Ende.', 'grammar_tip': 'Adverb + Inversion, Nebensatz + Verb am Ende.'},
    {'id': 'gen_kon_019', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren', 'data': {'text': 'Wenn du früher kommst, können wir anfangen, obwohl noch nicht alle da sind.', 'verbs': ['kommst', 'können', 'anfangen', 'sind'], 'clause_type': 'complex_mixed'}, 'grammar_rule': 'Im wenn- und obwohl-Satz steht das Verb am Ende; der Hauptsatz bleibt mit Verb an Position 2.', 'grammar_tip': 'Jeder Nebensatz hat sein eigenes Verb am Schluss.'},
    {'id': 'gen_kon_020', 'module': 'konnektoren', 'type': 'reconstruction', 'level': 4, 'topic': 'complex_konnektoren', 'data': {'text': 'Er arbeitet viel, dennoch findet er Zeit für seine Familie, weil sie ihm wichtig ist.', 'verbs': ['arbeitet', 'findet', 'ist'], 'clause_type': 'complex_mixed'}, 'grammar_rule': '„Dennoch“ führt zur Inversion im Hauptsatz; im weil-Satz steht das Verb am Ende.', 'grammar_tip': 'Adverb + Inversion, weil + Verb ans Ende.'},
]

