"""
Nominalization (Nominalisierung & Umformung) — Exercise Bank.

Tests Nebensatz→Nominalphrase, Verb→Nomen,
Relativsatz→Partizipialattribut, and Satz→Infinitivkonstruktion.
Exercise type: transformation
"""

NOMINALISIERUNG_BANK = [
    {'id': 'gen_nom_001', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Weil es stark regnet, bleiben wir zu Hause.', 'target_words': ['Wegen', 'des', 'starken', 'Regens', 'bleiben', 'wir', 'zu', 'Hause'], 'correct_order': 'Wegen des starken Regens bleiben wir zu Hause.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Ein weil-Satz kann durch wegen + Genitiv nominalisiert werden.', 'grammar_tip': 'Weil → wegen + Genitiv.'},
    {'id': 'gen_nom_002', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Weil der Zug verspätet war, kamen wir zu spät.', 'target_words': ['Wegen', 'der', 'Verspaetung', 'des', 'Zuges', 'kamen', 'wir', 'zu', 'spaet'], 'correct_order': 'Wegen der Verspaetung des Zuges kamen wir zu spaet.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Der Kausalsatz mit weil wird zu wegen + Genitiv.', 'grammar_tip': 'Verspätet war → Verspätung.'},
    {'id': 'gen_nom_003', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Wenn man regelmäßig trainiert, bleibt man gesund.', 'target_words': ['Bei', 'regelmaessigem', 'Training', 'bleibt', 'man', 'gesund'], 'correct_order': 'Bei regelmaessigem Training bleibt man gesund.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Ein wenn-Satz kann mit bei + Dativ nominalisiert werden.', 'grammar_tip': 'Wenn → bei + Dativ.'},
    {'id': 'gen_nom_004', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Dass er abgesagt hat, überrascht uns.', 'target_words': ['Die', 'Absage', 'ueberrascht', 'uns'], 'correct_order': 'Die Absage ueberrascht uns.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Ein dass-Satz kann durch ein entsprechendes Nomen ersetzt werden.', 'grammar_tip': 'Dass er absagt → die Absage.'},
    {'id': 'gen_nom_005', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Weil die Preise steigen, gibt es Proteste.', 'target_words': ['Wegen', 'der', 'steigenden', 'Preise', 'gibt', 'es', 'Proteste'], 'correct_order': 'Wegen der steigenden Preise gibt es Proteste.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Der Nebensatz wird durch eine Nominalphrase mit Genitiv ersetzt.', 'grammar_tip': 'Steigen → steigenden Preise.'},
    {'id': 'gen_nom_006', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Wenn die Nachfrage wächst, expandiert das Unternehmen.', 'target_words': ['Bei', 'wachsender', 'Nachfrage', 'expandiert', 'das', 'Unternehmen'], 'correct_order': 'Bei wachsender Nachfrage expandiert das Unternehmen.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Wenn-Sätze können mit bei + Partizipialattribut umgeformt werden.', 'grammar_tip': 'Wächst → wachsender.'},
    {'id': 'gen_nom_007', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Weil er krank war, blieb er zu Hause.', 'target_words': ['Wegen', 'seiner', 'Krankheit', 'blieb', 'er', 'zu', 'Hause'], 'correct_order': 'Wegen seiner Krankheit blieb er zu Hause.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Weil + Subjekt + war → wegen + Genitiv + Nomen.', 'grammar_tip': 'krank war → Krankheit.'},
    {'id': 'gen_nom_008', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Dass sie erfolgreich ist, freut uns.', 'target_words': ['Ihr', 'Erfolg', 'freut', 'uns'], 'correct_order': 'Ihr Erfolg freut uns.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Ein dass-Satz wird durch ein entsprechendes Substantiv ersetzt.', 'grammar_tip': 'Erfolgreich ist → Erfolg.'},
    {'id': 'gen_nom_009', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Wenn man vorsichtig fährt, vermeidet man Unfälle.', 'target_words': ['Bei', 'vorsichtiger', 'Fahrweise', 'vermeidet', 'man', 'Unfaelle'], 'correct_order': 'Bei vorsichtiger Fahrweise vermeidet man Unfaelle.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Handlung im wenn-Satz wird als abstraktes Nomen ausgedrückt.', 'grammar_tip': 'Fährt → Fahrweise.'},
    {'id': 'gen_nom_010', 'module': 'nominalisierung', 'type': 'transformation', 'level': 3, 'topic': 'nebensatz_zu_nominal', 'data': {'source': 'Weil er zu spät kam, begann die Sitzung ohne ihn.', 'target_words': ['Wegen', 'seiner', 'Verspaetung', 'begann', 'die', 'Sitzung', 'ohne', 'ihn'], 'correct_order': 'Wegen seiner Verspaetung begann die Sitzung ohne ihn.', 'optional_words': [], 'transform_type': 'nebensatz_zu_nominal'}, 'grammar_rule': 'Zeitangaben mit weil können durch wegen + Genitiv ersetzt werden.', 'grammar_tip': 'Zu spät kam → Verspätung.'},
    {'id': 'gen_nom_011', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'verb_zu_nomen', 'data': {'source': 'Er reist im Sommer.', 'target_words': ['Seine', 'Reise', 'findet', 'im', 'Sommer', 'statt'], 'correct_order': 'Seine Reise findet im Sommer statt.', 'optional_words': [], 'transform_type': 'verb_zu_nomen'}, 'grammar_rule': 'Ein Verb kann durch ein entsprechendes Substantiv ersetzt werden.', 'grammar_tip': 'verreisen → Reise.'},
    {'id': 'gen_nom_012', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'verb_zu_nomen', 'data': {'source': 'Die Firma investiert stark.', 'target_words': ['Die', 'starken', 'Investitionen', 'der', 'Firma', 'sind', 'bemerkenswert'], 'correct_order': 'Die starken Investitionen der Firma sind bemerkenswert.', 'optional_words': [], 'transform_type': 'verb_zu_nomen'}, 'grammar_rule': 'Verbale Handlung wird durch ein Nomen mit Genitivergänzung ersetzt.', 'grammar_tip': 'investiert → Investitionen.'},
    {'id': 'gen_nom_013', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'relativsatz_zu_partizip', 'data': {'source': 'Die Studenten, die im Ausland studieren, sammeln Erfahrungen.', 'target_words': ['Die', 'im', 'Ausland', 'studierenden', 'Studenten', 'sammeln', 'Erfahrungen'], 'correct_order': 'Die im Ausland studierenden Studenten sammeln Erfahrungen.', 'optional_words': [], 'transform_type': 'relativsatz_zu_partizip'}, 'grammar_rule': 'Ein Relativsatz kann durch ein Partizip I als Attribut ersetzt werden.', 'grammar_tip': 'die studieren → studierenden.'},
    {'id': 'gen_nom_014', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'relativsatz_zu_partizip', 'data': {'source': 'Die Daten, die analysiert wurden, sind vertraulich.', 'target_words': ['Die', 'analysierten', 'Daten', 'sind', 'vertraulich'], 'correct_order': 'Die analysierten Daten sind vertraulich.', 'optional_words': [], 'transform_type': 'relativsatz_zu_partizip'}, 'grammar_rule': 'Relativsätze im Passiv können durch Partizip II-Attribute ersetzt werden.', 'grammar_tip': 'die analysiert wurden → analysierten.'},
    {'id': 'gen_nom_015', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'satz_zu_infinitiv', 'data': {'source': 'Er will das Projekt beenden.', 'target_words': ['Sein', 'Ziel', 'ist', 'es', 'das', 'Projekt', 'zu', 'beenden'], 'correct_order': 'Sein Ziel ist es, das Projekt zu beenden.', 'optional_words': ['es'], 'transform_type': 'satz_zu_infinitiv'}, 'grammar_rule': 'Ein Hauptsatz kann durch eine Infinitivkonstruktion mit zu ergänzt werden.', 'grammar_tip': 'Ziel ist es zu.'},
    {'id': 'gen_nom_016', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'satz_zu_infinitiv', 'data': {'source': 'Er hat beschlossen, dass er kündigt.', 'target_words': ['Er', 'hat', 'beschlossen', 'zu', 'kuendigen'], 'correct_order': 'Er hat beschlossen, zu kuendigen.', 'optional_words': [], 'transform_type': 'satz_zu_infinitiv'}, 'grammar_rule': 'Ein dass-Satz kann durch eine zu-Infinitivkonstruktion ersetzt werden.', 'grammar_tip': 'beschließen zu.'},
    {'id': 'gen_nom_017', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'verb_zu_nomen', 'data': {'source': 'Die Regierung reformiert das Bildungssystem.', 'target_words': ['Die', 'Reform', 'des', 'Bildungssystems', 'durch', 'die', 'Regierung', 'ist', 'umstritten'], 'correct_order': 'Die Reform des Bildungssystems durch die Regierung ist umstritten.', 'optional_words': [], 'transform_type': 'verb_zu_nomen'}, 'grammar_rule': 'Verb wird zu Nomen mit Genitivergänzung und Präpositionalattribut.', 'grammar_tip': 'reformiert → Reform.'},
    {'id': 'gen_nom_018', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'relativsatz_zu_partizip', 'data': {'source': 'Die Mitarbeiter, die motiviert sind, arbeiten effizient.', 'target_words': ['Die', 'motivierten', 'Mitarbeiter', 'arbeiten', 'effizient'], 'correct_order': 'Die motivierten Mitarbeiter arbeiten effizient.', 'optional_words': [], 'transform_type': 'relativsatz_zu_partizip'}, 'grammar_rule': 'Relativsätze mit sein + Adjektiv können zu attributiven Adjektiven werden.', 'grammar_tip': 'die motiviert sind → motivierten.'},
    {'id': 'gen_nom_019', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'satz_zu_infinitiv', 'data': {'source': 'Es ist wichtig, dass man pünktlich erscheint.', 'target_words': ['Es', 'ist', 'wichtig', 'puenktlich', 'zu', 'erscheinen'], 'correct_order': 'Es ist wichtig, puenktlich zu erscheinen.', 'optional_words': [], 'transform_type': 'satz_zu_infinitiv'}, 'grammar_rule': 'Ein dass-Satz kann durch eine zu-Infinitivkonstruktion ersetzt werden.', 'grammar_tip': 'wichtig zu.'},
    {'id': 'gen_nom_020', 'module': 'nominalisierung', 'type': 'transformation', 'level': 4, 'topic': 'verb_zu_nomen', 'data': {'source': 'Das Unternehmen expandiert international.', 'target_words': ['Die', 'internationale', 'Expansion', 'des', 'Unternehmens', 'ist', 'erfolgreich'], 'correct_order': 'Die internationale Expansion des Unternehmens ist erfolgreich.', 'optional_words': [], 'transform_type': 'verb_zu_nomen'}, 'grammar_rule': 'Ein Verb kann in ein entsprechendes Nomen mit Genitiv umgewandelt werden.', 'grammar_tip': 'expandiert → Expansion.'},
]

