"""
Passive Voice (Passiv) — Exercise Bank.

Tests Vorgangspassiv (Präsens, Präteritum, Perfekt),
Zustandspassiv, and Passiversatzformen.
Exercise type: transformation
"""

PASSIV_BANK = [
    {'id': 'gen_pass_001', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Der Koch bereitet das Essen zu.', 'target_words': ['Das', 'Essen', 'wird', 'von', 'dem', 'Koch', 'zubereitet'], 'correct_order': 'Das Essen wird von dem Koch zubereitet.', 'optional_words': ['von', 'dem', 'Koch'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Im Vorgangspassiv Präsens wird das Akkusativobjekt zum Subjekt und es steht werden + Partizip II.', 'grammar_tip': 'Objekt wird Subjekt + wird + Partizip.'},
    {'id': 'gen_pass_002', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Die Firma produziert neue Autos.', 'target_words': ['Neue', 'Autos', 'werden', 'von', 'der', 'Firma', 'produziert'], 'correct_order': 'Neue Autos werden von der Firma produziert.', 'optional_words': ['von', 'der', 'Firma'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Im Präsenspassiv steht werden im Präsens und das Partizip II am Ende.', 'grammar_tip': 'werden + Partizip II.'},
    {'id': 'gen_pass_003', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Der Lehrer erklärt die Regel.', 'target_words': ['Die', 'Regel', 'wird', 'von', 'dem', 'Lehrer', 'erklaert'], 'correct_order': 'Die Regel wird von dem Lehrer erklaert.', 'optional_words': ['von', 'dem', 'Lehrer'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Das Akkusativobjekt wird Subjekt, werden steht an Position 2.', 'grammar_tip': 'Passiv = Fokus auf Handlung.'},
    {'id': 'gen_pass_004', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Die Polizei kontrolliert die Autos.', 'target_words': ['Die', 'Autos', 'werden', 'von', 'der', 'Polizei', 'kontrolliert'], 'correct_order': 'Die Autos werden von der Polizei kontrolliert.', 'optional_words': ['von', 'der', 'Polizei'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Im Vorgangspassiv Präsens wird das Objekt Subjekt und werden konjugiert.', 'grammar_tip': 'werden zeigt Prozess.'},
    {'id': 'gen_pass_005', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Man baut ein neues Krankenhaus.', 'target_words': ['Ein', 'neues', 'Krankenhaus', 'wird', 'gebaut'], 'correct_order': 'Ein neues Krankenhaus wird gebaut.', 'optional_words': [], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Unpersönliches Subjekt fällt weg, Objekt wird Subjekt.', 'grammar_tip': 'Man verschwindet im Passiv.'},
    {'id': 'gen_pass_006', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Der Mechaniker repariert das Auto.', 'target_words': ['Das', 'Auto', 'wird', 'von', 'dem', 'Mechaniker', 'repariert'], 'correct_order': 'Das Auto wird von dem Mechaniker repariert.', 'optional_words': ['von', 'dem', 'Mechaniker'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'werden + Partizip II bildet das Vorgangspassiv.', 'grammar_tip': 'wird repariert.'},
    {'id': 'gen_pass_007', 'module': 'passiv', 'type': 'transformation', 'level': 2, 'topic': 'vorgangspassiv_praesens', 'data': {'source': 'Die Redaktion veröffentlicht den Artikel.', 'target_words': ['Der', 'Artikel', 'wird', 'von', 'der', 'Redaktion', 'veroeffentlicht'], 'correct_order': 'Der Artikel wird von der Redaktion veroeffentlicht.', 'optional_words': ['von', 'der', 'Redaktion'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Das Akkusativobjekt wird zum Nominativ im Passiv.', 'grammar_tip': 'Objekt tauscht Rolle.'},
    {'id': 'gen_pass_008', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'vorgangspassiv_praeteritum', 'data': {'source': 'Der Chef lobte die Mitarbeiter.', 'target_words': ['Die', 'Mitarbeiter', 'wurden', 'von', 'dem', 'Chef', 'gelobt'], 'correct_order': 'Die Mitarbeiter wurden von dem Chef gelobt.', 'optional_words': ['von', 'dem', 'Chef'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Im Präteritum steht wurden + Partizip II.', 'grammar_tip': 'Präteritum: wurden + Partizip.'},
    {'id': 'gen_pass_009', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'vorgangspassiv_perfekt', 'data': {'source': 'Die Firma hat das Projekt gestartet.', 'target_words': ['Das', 'Projekt', 'ist', 'von', 'der', 'Firma', 'gestartet', 'worden'], 'correct_order': 'Das Projekt ist von der Firma gestartet worden.', 'optional_words': ['von', 'der', 'Firma'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Im Perfektpassiv: sein + Partizip II + worden.', 'grammar_tip': 'ist gemacht worden.'},
    {'id': 'gen_pass_010', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'zustandspassiv', 'data': {'source': 'Der Techniker hat die Tür geschlossen.', 'target_words': ['Die', 'Tür', 'ist', 'geschlossen'], 'correct_order': 'Die Tür ist geschlossen.', 'optional_words': [], 'transform_type': 'aktiv_zu_zustandspassiv'}, 'grammar_rule': 'Zustandspassiv beschreibt das Ergebnis: sein + Partizip II.', 'grammar_tip': 'sein zeigt Zustand.'},
    {'id': 'gen_pass_011', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'zustandspassiv', 'data': {'source': 'Die Putzfrau hat das Fenster geöffnet.', 'target_words': ['Das', 'Fenster', 'ist', 'geoeffnet'], 'correct_order': 'Das Fenster ist geoeffnet.', 'optional_words': [], 'transform_type': 'aktiv_zu_zustandspassiv'}, 'grammar_rule': 'sein + Partizip II beschreibt den Zustand nach der Handlung.', 'grammar_tip': 'Zustand nicht Prozess.'},
    {'id': 'gen_pass_012', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'vorgangspassiv_praeteritum', 'data': {'source': 'Die Regierung beschloss neue Maßnahmen.', 'target_words': ['Neue', 'Massnahmen', 'wurden', 'von', 'der', 'Regierung', 'beschlossen'], 'correct_order': 'Neue Massnahmen wurden von der Regierung beschlossen.', 'optional_words': ['von', 'der', 'Regierung'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Im Präteritum steht wurden + Partizip II.', 'grammar_tip': 'wurden gemacht.'},
    {'id': 'gen_pass_013', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'vorgangspassiv_perfekt', 'data': {'source': 'Der Arzt hat den Patienten untersucht.', 'target_words': ['Der', 'Patient', 'ist', 'von', 'dem', 'Arzt', 'untersucht', 'worden'], 'correct_order': 'Der Patient ist von dem Arzt untersucht worden.', 'optional_words': ['von', 'dem', 'Arzt'], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Perfektpassiv: ist + Partizip II + worden.', 'grammar_tip': 'ist + worden.'},
    {'id': 'gen_pass_014', 'module': 'passiv', 'type': 'transformation', 'level': 3, 'topic': 'zustandspassiv', 'data': {'source': 'Man hat alle Tickets verkauft.', 'target_words': ['Alle', 'Tickets', 'sind', 'verkauft'], 'correct_order': 'Alle Tickets sind verkauft.', 'optional_words': [], 'transform_type': 'aktiv_zu_zustandspassiv'}, 'grammar_rule': 'Zustandspassiv mit sein beschreibt das Ergebnis.', 'grammar_tip': 'sein + Partizip = Zustand.'},
    {'id': 'gen_pass_015', 'module': 'passiv', 'type': 'transformation', 'level': 4, 'topic': 'passiv_ersatzform', 'data': {'source': 'Man kann das Problem leicht lösen.', 'target_words': ['Das', 'Problem', 'laesst', 'sich', 'leicht', 'loesen'], 'correct_order': 'Das Problem laesst sich leicht loesen.', 'optional_words': [], 'transform_type': 'passiv_zu_ersatzform'}, 'grammar_rule': 'sich lassen + Infinitiv ist eine Passiversatzform.', 'grammar_tip': 'laesst sich = kann passiv.'},
    {'id': 'gen_pass_016', 'module': 'passiv', 'type': 'transformation', 'level': 4, 'topic': 'passiv_ersatzform', 'data': {'source': 'Man liest das Buch gut.', 'target_words': ['Das', 'Buch', 'ist', 'gut', 'lesbar'], 'correct_order': 'Das Buch ist gut lesbar.', 'optional_words': [], 'transform_type': 'passiv_zu_ersatzform'}, 'grammar_rule': 'Adjektive auf -bar drücken eine passive Möglichkeit aus.', 'grammar_tip': '-bar = kann werden.'},
    {'id': 'gen_pass_017', 'module': 'passiv', 'type': 'transformation', 'level': 4, 'topic': 'passiv_ersatzform', 'data': {'source': 'Man repariert das Gerät nicht.', 'target_words': ['Das', 'Geraet', 'laesst', 'sich', 'nicht', 'reparieren'], 'correct_order': 'Das Geraet laesst sich nicht reparieren.', 'optional_words': [], 'transform_type': 'passiv_zu_ersatzform'}, 'grammar_rule': 'sich lassen ersetzt das Passiv und zeigt Möglichkeit.', 'grammar_tip': 'laesst sich = kann.'},
    {'id': 'gen_pass_018', 'module': 'passiv', 'type': 'transformation', 'level': 4, 'topic': 'passiv_ersatzform', 'data': {'source': 'Man sieht die Berge von hier.', 'target_words': ['Von', 'hier', 'sieht', 'man', 'die', 'Berge'], 'correct_order': 'Von hier sieht man die Berge.', 'optional_words': [], 'transform_type': 'passiv_zu_ersatzform'}, 'grammar_rule': 'Unpersönliches man dient als Passiversatz.', 'grammar_tip': 'man = unpersönlich.'},
    {'id': 'gen_pass_019', 'module': 'passiv', 'type': 'transformation', 'level': 4, 'topic': 'passiv_ersatzform', 'data': {'source': 'Man kann die Datei einfach öffnen.', 'target_words': ['Die', 'Datei', 'ist', 'einfach', 'oeffnbar'], 'correct_order': 'Die Datei ist einfach oeffnbar.', 'optional_words': [], 'transform_type': 'passiv_zu_ersatzform'}, 'grammar_rule': '-bar bildet eine passive Bedeutung.', 'grammar_tip': 'oeffnbar = kann geoeffnet werden.'},
    {'id': 'gen_pass_020', 'module': 'passiv', 'type': 'transformation', 'level': 4, 'topic': 'passiv_ersatzform', 'data': {'source': 'Man diskutiert dieses Thema oft.', 'target_words': ['Dieses', 'Thema', 'wird', 'oft', 'diskutiert'], 'correct_order': 'Dieses Thema wird oft diskutiert.', 'optional_words': [], 'transform_type': 'aktiv_zu_passiv'}, 'grammar_rule': 'Auch ohne Agens kann das Vorgangspassiv verwendet werden.', 'grammar_tip': 'Agens kann weggelassen werden.'},
]

