"""
Prepositions & Cases (Präpositionen & Kasus) — Exercise Bank.

Tests Wechselpräpositionen (Akkusativ vs Dativ),
fixed-case prepositions, Genitiv prepositions,
and verb+preposition idioms.
Exercise type: quick_select
"""

PRAEPOSITIONEN_BANK = [
    {'id': 'gen_praep_001', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Ich lege das Buch {gap_1} Tisch.', 'gaps': [{'position': 'gap_1', 'options': ['auf den', 'auf dem', 'an den', 'auf das'], 'answer': 'auf den', 'explanation': 'Wohin? -> Akkusativ (Bewegung). Tisch = maskulin -> den.'}]}, 'grammar_rule': 'Wechselpräpositionen nehmen Akkusativ bei Bewegung (Wohin?).', 'grammar_tip': 'Wohin? = Akkusativ.'},
    {'id': 'gen_praep_002', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Das Bild hängt {gap_1} Wand.', 'gaps': [{'position': 'gap_1', 'options': ['an der', 'an die', 'auf der', 'an den'], 'answer': 'an der', 'explanation': 'Wo? -> Dativ (Position). Wand = feminin -> der.'}]}, 'grammar_rule': 'Wechselpräpositionen nehmen Dativ bei Lage (Wo?).', 'grammar_tip': 'Wo? = Dativ.'},
    {'id': 'gen_praep_003', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Die Kinder laufen {gap_1} Park.', 'gaps': [{'position': 'gap_1', 'options': ['in den', 'im', 'in dem', 'in der'], 'answer': 'in den', 'explanation': 'Wohin? -> Akkusativ. Park = maskulin -> den.'}]}, 'grammar_rule': 'Bei Richtungsangabe mit Wechselpräposition -> Akkusativ.', 'grammar_tip': 'Bewegung = Akkusativ.'},
    {'id': 'gen_praep_004', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Wir sitzen {gap_1} Sofa.', 'gaps': [{'position': 'gap_1', 'options': ['auf dem', 'auf den', 'an dem', 'auf das'], 'answer': 'auf dem', 'explanation': 'Wo? -> Dativ. Sofa = neutrum -> dem.'}]}, 'grammar_rule': 'Wechselpräposition + statische Position -> Dativ.', 'grammar_tip': 'Keine Bewegung = Dativ.'},
    {'id': 'gen_praep_005', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Er stellt die Blumen {gap_1} Fenster.', 'gaps': [{'position': 'gap_1', 'options': ['vor das', 'vor dem', 'an das', 'vor den'], 'answer': 'vor das', 'explanation': 'Wohin? -> Akkusativ. Fenster = neutrum -> das.'}]}, 'grammar_rule': 'Wechselpräposition bei Richtung -> Akkusativ.', 'grammar_tip': 'Stellen = Bewegung.'},
    {'id': 'gen_praep_006', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Das Auto steht {gap_1} Haus.', 'gaps': [{'position': 'gap_1', 'options': ['vor dem', 'vor das', 'an dem', 'vor den'], 'answer': 'vor dem', 'explanation': 'Wo? -> Dativ. Haus = neutrum -> dem.'}]}, 'grammar_rule': 'Bei Lage mit Wechselpräposition -> Dativ.', 'grammar_tip': 'Stehen = Dativ.'},
    {'id': 'gen_praep_007', 'module': 'praepositionen', 'type': 'quick_select', 'level': 1, 'topic': 'wechselpraep', 'data': {'sentence': 'Sie geht {gap_1} Brücke.', 'gaps': [{'position': 'gap_1', 'options': ['über die', 'über der', 'auf die', 'an die'], 'answer': 'über die', 'explanation': 'Wohin? -> Akkusativ. Brücke = feminin -> die.'}]}, 'grammar_rule': 'Wechselpräposition + Bewegung -> Akkusativ.', 'grammar_tip': 'Gehen = Wohin?'},
    {'id': 'gen_praep_008', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'akkusativ_praep', 'data': {'sentence': 'Das Geschenk ist {gap_1} dich.', 'gaps': [{'position': 'gap_1', 'options': ['für', 'mit', 'von', 'zu'], 'answer': 'für', 'explanation': '„Für“ verlangt immer den Akkusativ.'}]}, 'grammar_rule': 'Präpositionen wie für verlangen Akkusativ.', 'grammar_tip': 'FUDOGUB = Akkusativ.'},
    {'id': 'gen_praep_009', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'dativ_praep', 'data': {'sentence': 'Ich fahre {gap_1} Zug.', 'gaps': [{'position': 'gap_1', 'options': ['mit dem', 'mit den', 'für den', 'zu dem'], 'answer': 'mit dem', 'explanation': '„Mit“ verlangt Dativ. Zug = maskulin -> dem.'}]}, 'grammar_rule': 'Mit, nach, aus, bei, seit, von, zu verlangen Dativ.', 'grammar_tip': 'Mit = Dativ.'},
    {'id': 'gen_praep_010', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'akkusativ_praep', 'data': {'sentence': 'Wir gehen {gap_1} Park.', 'gaps': [{'position': 'gap_1', 'options': ['durch den', 'durch dem', 'mit dem', 'bei dem'], 'answer': 'durch den', 'explanation': '„Durch“ verlangt Akkusativ. Park = maskulin -> den.'}]}, 'grammar_rule': 'Durch gehört zu den Akkusativpräpositionen.', 'grammar_tip': 'Durch = Akkusativ.'},
    {'id': 'gen_praep_011', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'dativ_praep', 'data': {'sentence': 'Er wohnt {gap_1} seinen Eltern.', 'gaps': [{'position': 'gap_1', 'options': ['bei', 'für', 'durch', 'um'], 'answer': 'bei', 'explanation': '„Bei“ verlangt Dativ.'}]}, 'grammar_rule': 'Bei steht mit Dativ.', 'grammar_tip': 'Bei = Dativ.'},
    {'id': 'gen_praep_012', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'akkusativ_praep', 'data': {'sentence': 'Er kommt {gap_1} dich.', 'gaps': [{'position': 'gap_1', 'options': ['gegen', 'mit', 'von', 'zu'], 'answer': 'gegen', 'explanation': '„Gegen“ verlangt Akkusativ.'}]}, 'grammar_rule': 'Gegen steht mit Akkusativ.', 'grammar_tip': 'Gegen = Akkusativ.'},
    {'id': 'gen_praep_013', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'dativ_praep', 'data': {'sentence': 'Seit {gap_1} Jahr lerne ich Deutsch.', 'gaps': [{'position': 'gap_1', 'options': ['einem', 'einen', 'ein', 'eines'], 'answer': 'einem', 'explanation': '„Seit“ verlangt Dativ.'}]}, 'grammar_rule': 'Seit steht mit Dativ.', 'grammar_tip': 'Seit = Dativ.'},
    {'id': 'gen_praep_014', 'module': 'praepositionen', 'type': 'quick_select', 'level': 2, 'topic': 'dativ_praep', 'data': {'sentence': 'Ich komme gerade {gap_1} Arbeit.', 'gaps': [{'position': 'gap_1', 'options': ['von der', 'für die', 'durch die', 'um die'], 'answer': 'von der', 'explanation': '„Von“ verlangt Dativ. Arbeit = feminin -> der.'}]}, 'grammar_rule': 'Von steht mit Dativ.', 'grammar_tip': 'Von = Dativ.'},
    {'id': 'gen_praep_015', 'module': 'praepositionen', 'type': 'quick_select', 'level': 3, 'topic': 'genitiv_praep', 'data': {'sentence': '{gap_1} schlechten Wetters bleiben wir zu Hause.', 'gaps': [{'position': 'gap_1', 'options': ['Wegen des', 'Wegen dem', 'Trotz dem', 'Während dem'], 'answer': 'Wegen des', 'explanation': '„Wegen“ verlangt Genitiv. Wetter = neutrum -> des.'}]}, 'grammar_rule': 'Wegen, trotz, während, anstatt verlangen Genitiv.', 'grammar_tip': 'Genitiv bei wegen.'},
    {'id': 'gen_praep_016', 'module': 'praepositionen', 'type': 'quick_select', 'level': 3, 'topic': 'genitiv_praep', 'data': {'sentence': '{gap_1} starken Regens fiel das Konzert aus.', 'gaps': [{'position': 'gap_1', 'options': ['Trotz des', 'Trotz dem', 'Wegen dem', 'Während dem'], 'answer': 'Trotz des', 'explanation': '„Trotz“ verlangt Genitiv.'}]}, 'grammar_rule': 'Trotz + Genitiv.', 'grammar_tip': 'Trotz des.'},
    {'id': 'gen_praep_017', 'module': 'praepositionen', 'type': 'quick_select', 'level': 3, 'topic': 'verb_praep', 'data': {'sentence': 'Ich warte schon lange {gap_1} Bus.', 'gaps': [{'position': 'gap_1', 'options': ['auf den', 'auf dem', 'für den', 'mit dem'], 'answer': 'auf den', 'explanation': '„Warten auf“ verlangt Akkusativ.'}]}, 'grammar_rule': 'Bestimmte Verben stehen mit festen Präpositionen.', 'grammar_tip': 'Warten auf + Akk.'},
    {'id': 'gen_praep_018', 'module': 'praepositionen', 'type': 'quick_select', 'level': 3, 'topic': 'verb_praep', 'data': {'sentence': 'Sie freut sich sehr {gap_1} Geschenk.', 'gaps': [{'position': 'gap_1', 'options': ['über das', 'über dem', 'auf das', 'für das'], 'answer': 'über das', 'explanation': '„Sich freuen über“ verlangt Akkusativ.'}]}, 'grammar_rule': 'Sich freuen über + Akkusativ.', 'grammar_tip': 'Freuen über = Akk.'},
    {'id': 'gen_praep_019', 'module': 'praepositionen', 'type': 'quick_select', 'level': 3, 'topic': 'genitiv_praep', 'data': {'sentence': '{gap_1} des Films hat niemand gesprochen.', 'gaps': [{'position': 'gap_1', 'options': ['Während', 'Mit', 'Für', 'Durch'], 'answer': 'Während', 'explanation': '„Während“ verlangt Genitiv.'}]}, 'grammar_rule': 'Während + Genitiv.', 'grammar_tip': 'Während des.'},
    {'id': 'gen_praep_020', 'module': 'praepositionen', 'type': 'quick_select', 'level': 3, 'topic': 'verb_praep', 'data': {'sentence': 'Er interessiert sich sehr {gap_1} Politik.', 'gaps': [{'position': 'gap_1', 'options': ['für die', 'für der', 'an die', 'mit der'], 'answer': 'für die', 'explanation': '„Sich interessieren für“ verlangt Akkusativ.'}]}, 'grammar_rule': 'Verb + feste Präposition bestimmt den Kasus.', 'grammar_tip': 'Interessieren für + Akk.'},
]

