"""
Relative Clauses (Relativsätze) — Exercise Bank.

Tests Nominativ/Akkusativ/Dativ relative pronouns,
prepositions with relative pronouns, Genitiv (dessen/deren),
was/wo relative clauses, and nested relatives.
Exercise type: reconstruction
"""

RELATIV_BANK = [
    # ===== EXISTING (now with English translations added) =====
    {'id': 'gen_rel_001', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Der Mann, der neben mir wohnt, ist Arzt.',
              'english': 'The man who lives next to me is a doctor.',
              'verbs': ['wohnt', 'ist'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Der Mann ist Arzt.', 'sentence_b': 'Der Mann wohnt neben mir.'},
     'grammar_rule': '„Der“ steht im Nominativ, weil es Subjekt im Relativsatz ist und sich auf „der Mann“ (maskulin) bezieht.',
     'grammar_tip': 'Relativpronomen richtet sich nach Funktion im Nebensatz.'},

    {'id': 'gen_rel_002', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Das Buch, das ich lese, ist spannend.',
              'english': 'The book that I am reading is exciting.',
              'verbs': ['lese', 'ist'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Das Buch ist spannend.', 'sentence_b': 'Ich lese das Buch.'},
     'grammar_rule': '„Das“ steht im Akkusativ, weil es Objekt von „lese“ ist.',
     'grammar_tip': 'Frage im Nebensatz: Wen oder was?'},

    {'id': 'gen_rel_003', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Die Frau, die dort arbeitet, kommt aus Spanien.',
              'english': 'The woman who works there comes from Spain.',
              'verbs': ['arbeitet', 'kommt'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Die Frau kommt aus Spanien.', 'sentence_b': 'Die Frau arbeitet dort.'},
     'grammar_rule': '„Die“ steht im Nominativ, da es Subjekt im Relativsatz ist.',
     'grammar_tip': 'Subjekt im Nebensatz = Nominativ.'},

    {'id': 'gen_rel_004', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Der Film, den wir gestern gesehen haben, war lang.',
              'english': 'The film that we watched yesterday was long.',
              'verbs': ['gesehen', 'haben', 'war'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Der Film war lang.', 'sentence_b': 'Wir haben den Film gestern gesehen.'},
     'grammar_rule': '„Den“ steht im Akkusativ, da es Objekt von „gesehen haben“ ist.',
     'grammar_tip': 'Maskulin Akkusativ = den.'},

    {'id': 'gen_rel_005', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Das Kind, das im Garten spielt, ist mein Neffe.',
              'english': 'The child who is playing in the garden is my nephew.',
              'verbs': ['spielt', 'ist'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Das Kind ist mein Neffe.', 'sentence_b': 'Das Kind spielt im Garten.'},
     'grammar_rule': '„Das“ ist Nominativ, da es Subjekt von „spielt“ ist.',
     'grammar_tip': 'Neutrum bleibt das.'},

    {'id': 'gen_rel_006', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Die Stadt, die wir besuchen, ist sehr alt.',
              'english': 'The city that we are visiting is very old.',
              'verbs': ['besuchen', 'ist'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Die Stadt ist sehr alt.', 'sentence_b': 'Wir besuchen die Stadt.'},
     'grammar_rule': '„Die“ steht im Akkusativ, da es Objekt im Relativsatz ist.',
     'grammar_tip': 'Plural oder feminin Akkusativ = die.'},

    {'id': 'gen_rel_007', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Der Kuchen, den sie gebacken hat, schmeckt gut.',
              'english': 'The cake that she baked tastes good.',
              'verbs': ['gebacken', 'hat', 'schmeckt'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Der Kuchen schmeckt gut.', 'sentence_b': 'Sie hat den Kuchen gebacken.'},
     'grammar_rule': '„Den“ ist Akkusativ, weil es direktes Objekt von „gebacken hat“ ist.',
     'grammar_tip': 'Verb am Ende im Relativsatz.'},

    {'id': 'gen_rel_008', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Der Mann, dem ich geholfen habe, bedankt sich.',
              'english': 'The man whom I helped thanks me.',
              'verbs': ['geholfen', 'habe', 'bedankt'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Der Mann bedankt sich.', 'sentence_b': 'Ich habe dem Mann geholfen.'},
     'grammar_rule': '„Dem“ steht im Dativ, da „helfen“ den Dativ verlangt.',
     'grammar_tip': 'helfen + Dativ.'},

    {'id': 'gen_rel_009', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Die Kollegin, mit der ich arbeite, ist sehr nett.',
              'english': 'The colleague I work with is very nice.',
              'verbs': ['arbeite', 'ist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Die Kollegin ist sehr nett.', 'sentence_b': 'Ich arbeite mit der Kollegin.'},
     'grammar_rule': 'Nach Präpositionen steht das Relativpronomen im entsprechenden Kasus.',
     'grammar_tip': 'mit + Dativ = mit der.'},

    {'id': 'gen_rel_010', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Kinder, denen wir helfen, sind dankbar.',
              'english': 'The children whom we help are grateful.',
              'verbs': ['helfen', 'sind'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Kinder sind dankbar.', 'sentence_b': 'Wir helfen den Kindern.'},
     'grammar_rule': '„Denen“ ist Dativ Plural, da helfen Dativ verlangt.',
     'grammar_tip': 'Plural Dativ = denen.'},

    {'id': 'gen_rel_011', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Das Haus, in dem er wohnt, ist alt.',
              'english': 'The house he lives in is old.',
              'verbs': ['wohnt', 'ist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Das Haus ist alt.', 'sentence_b': 'Er wohnt in dem Haus.'},
     'grammar_rule': 'Nach „in“ steht Dativ; daher „in dem“.',
     'grammar_tip': 'Präposition bestimmt den Kasus.'},

    {'id': 'gen_rel_012', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Frau, der ich vertraue, wohnt hier.',
              'english': 'The woman whom I trust lives here.',
              'verbs': ['vertraue', 'wohnt'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Frau wohnt hier.', 'sentence_b': 'Ich vertraue der Frau.'},
     'grammar_rule': '„Der“ ist Dativ feminin, da „vertrauen“ Dativ verlangt.',
     'grammar_tip': 'vertrauen + Dativ.'},

    {'id': 'gen_rel_013', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Der Freund, mit dem ich gesprochen habe, reist morgen ab.',
              'english': 'The friend I spoke with is leaving tomorrow.',
              'verbs': ['gesprochen', 'habe', 'reist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Der Freund reist morgen ab.', 'sentence_b': 'Ich habe mit dem Freund gesprochen.'},
     'grammar_rule': '„Mit dem“ steht im Dativ nach der Präposition mit.',
     'grammar_tip': 'mit + dem.'},

    {'id': 'gen_rel_014', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Stadt, der wir viel verdanken, feiert Jubiläum.',
              'english': 'The city to which we owe a lot is celebrating an anniversary.',
              'verbs': ['verdanken', 'feiert'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Stadt feiert Jubiläum.', 'sentence_b': 'Wir verdanken der Stadt viel.'},
     'grammar_rule': '„Der“ ist Dativ feminin wegen „verdanken“.',
     'grammar_tip': 'verdanken + Dativ.'},

    {'id': 'gen_rel_015', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen',
     'data': {'text': 'Der Autor, dessen Buch ich lese, kommt aus Österreich.',
              'english': 'The author whose book I am reading comes from Austria.',
              'verbs': ['lese', 'kommt'], 'clause_type': 'relativsatz_gen',
              'sentence_a': 'Der Autor kommt aus Österreich.', 'sentence_b': 'Ich lese das Buch des Autors.'},
     'grammar_rule': '„Dessen“ steht im Genitiv maskulin und zeigt Besitz an.',
     'grammar_tip': 'Genitiv Besitz = dessen/deren.'},

    {'id': 'gen_rel_016', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen',
     'data': {'text': 'Die Frau, deren Auto gestohlen wurde, ist verzweifelt.',
              'english': 'The woman whose car was stolen is desperate.',
              'verbs': ['gestohlen', 'wurde', 'ist'], 'clause_type': 'relativsatz_gen',
              'sentence_a': 'Die Frau ist verzweifelt.', 'sentence_b': 'Das Auto der Frau wurde gestohlen.'},
     'grammar_rule': '„Deren“ ist Genitiv feminin und zeigt Zugehörigkeit.',
     'grammar_tip': 'deren für feminin und Plural.'},

    {'id': 'gen_rel_017', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was',
     'data': {'text': 'Alles, was er sagt, klingt logisch.',
              'english': 'Everything he says sounds logical.',
              'verbs': ['sagt', 'klingt'], 'clause_type': 'relativsatz_was',
              'sentence_a': 'Alles klingt logisch.', 'sentence_b': 'Er sagt alles.'},
     'grammar_rule': 'Nach „alles“ verwendet man „was“ als Relativpronomen.',
     'grammar_tip': 'Alles + was.'},

    {'id': 'gen_rel_018', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was',
     'data': {'text': 'Das ist genau das, was ich erwartet habe.',
              'english': "That is exactly what I expected.",
              'verbs': ['erwartet', 'habe', 'ist'], 'clause_type': 'relativsatz_was',
              'sentence_a': 'Das ist genau das.', 'sentence_b': 'Ich habe das erwartet.'},
     'grammar_rule': 'Nach „das“ im Sinne von „dasjenige“ steht häufig „was“.',
     'grammar_tip': 'das, was ...'},

    {'id': 'gen_rel_019', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt',
     'data': {'text': 'Der Mann, der das Buch geschrieben hat, das ich lese, lebt in Berlin.',
              'english': 'The man who wrote the book that I am reading lives in Berlin.',
              'verbs': ['geschrieben', 'hat', 'lese', 'lebt'], 'clause_type': 'verschachtelte_relativsaetze',
              'sentence_a': 'Der Mann lebt in Berlin.',
              'sentence_b': 'Der Mann hat das Buch geschrieben. Ich lese das Buch.'},
     'grammar_rule': 'Mehrere Relativsätze beziehen sich jeweils auf ihr Bezugswort und stehen mit Verb am Ende.',
     'grammar_tip': 'Jeder Relativsatz hat eigenes Verb am Schluss.'},

    {'id': 'gen_rel_020', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt',
     'data': {'text': 'Die Stadt, in der ich studiert habe, die viele Parks hat, gefällt mir sehr.',
              'english': 'I really like the city where I studied, which has many parks.',
              'verbs': ['studiert', 'habe', 'hat', 'gefällt'], 'clause_type': 'verschachtelte_relativsaetze',
              'sentence_a': 'Die Stadt gefällt mir sehr.',
              'sentence_b': 'Ich habe in der Stadt studiert. Die Stadt hat viele Parks.'},
     'grammar_rule': 'Mehrere Relativsätze werden durch Kommas getrennt; jedes Verb steht am Ende des jeweiligen Nebensatzes.',
     'grammar_tip': 'Komma + Verb am Ende.'},

    # ===== NEW: Level 2 (10) — Nominativ/Akkusativ (life-related) =====
    {'id': 'gen_rel_021', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Der Kollege, der mir bei einem Projekt geholfen hat, arbeitet sehr genau.',
              'english': 'The colleague who helped me with a project works very precisely.',
              'verbs': ['geholfen', 'hat', 'arbeitet'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Der Kollege arbeitet sehr genau.', 'sentence_b': 'Der Kollege hat mir bei einem Projekt geholfen.'},
     'grammar_rule': '„Der“ steht im Nominativ, weil es Subjekt im Relativsatz ist (Bezug: der Kollege).',
     'grammar_tip': 'Subjekt im Relativsatz = Nominativ.'},

    {'id': 'gen_rel_022', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Das Excel, das ich gestern gebaut habe, spart mir viel Zeit.',
              'english': 'The Excel file that I built yesterday saves me a lot of time.',
              'verbs': ['gebaut', 'habe', 'spart'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Das Excel spart mir viel Zeit.', 'sentence_b': 'Ich habe das Excel gestern gebaut.'},
     'grammar_rule': '„Das“ steht im Akkusativ, weil es Objekt von „gebaut habe“ ist.',
     'grammar_tip': 'Wen/was? → Akkusativ.'},

    {'id': 'gen_rel_023', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Die Freundin, die mich motiviert, hilft mir beim Deutschlernen.',
              'english': 'The friend who motivates me helps me learn German.',
              'verbs': ['motiviert', 'hilft'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Die Freundin hilft mir beim Deutschlernen.', 'sentence_b': 'Die Freundin motiviert mich.'},
     'grammar_rule': '„Die“ steht im Nominativ, weil es Subjekt im Relativsatz ist (Bezug: die Freundin).',
     'grammar_tip': 'Subjekt = Nominativ.'},

    {'id': 'gen_rel_024', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Der Bericht, den ich heute abgeben muss, ist noch nicht fertig.',
              'english': 'The report that I have to submit today is not finished yet.',
              'verbs': ['abgeben', 'muss', 'ist'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Der Bericht ist noch nicht fertig.', 'sentence_b': 'Ich muss den Bericht heute abgeben.'},
     'grammar_rule': '„Den“ steht im Akkusativ, weil es Objekt im Relativsatz ist (den Bericht).',
     'grammar_tip': 'Maskulin Akkusativ = den.'},

    {'id': 'gen_rel_025', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Das Restaurant, das in der Nähe ist, hat oft lange Warteschlangen.',
              'english': 'The restaurant that is nearby often has long queues.',
              'verbs': ['ist', 'hat'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Das Restaurant hat oft lange Warteschlangen.', 'sentence_b': 'Das Restaurant ist in der Nähe.'},
     'grammar_rule': '„Das“ steht im Nominativ, weil es Subjekt von „ist“ ist.',
     'grammar_tip': 'Neutrum Subjekt = das.'},

    {'id': 'gen_rel_026', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Die App, die ich gerade baue, soll mir beim Lernen helfen.',
              'english': 'The app that I am building right now should help me learn.',
              'verbs': ['baue', 'soll'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Die App soll mir beim Lernen helfen.', 'sentence_b': 'Ich baue die App gerade.'},
     'grammar_rule': '„Die“ steht im Akkusativ, weil es Objekt von „baue“ ist (die App).',
     'grammar_tip': 'Feminin Akkusativ = die.'},

    {'id': 'gen_rel_027', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Der Podcast, der mir am meisten hilft, ist sehr klar gesprochen.',
              'english': 'The podcast that helps me the most is spoken very clearly.',
              'verbs': ['hilft', 'ist'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Der Podcast ist sehr klar gesprochen.', 'sentence_b': 'Der Podcast hilft mir am meisten.'},
     'grammar_rule': '„Der“ steht im Nominativ, weil es Subjekt von „hilft“ ist.',
     'grammar_tip': 'Subjekt = Nominativ.'},

    {'id': 'gen_rel_028', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Das Ticket, das ich gekauft habe, war nicht billig.',
              'english': 'The ticket that I bought was not cheap.',
              'verbs': ['gekauft', 'habe', 'war'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Das Ticket war nicht billig.', 'sentence_b': 'Ich habe das Ticket gekauft.'},
     'grammar_rule': '„Das“ steht im Akkusativ, weil es Objekt im Relativsatz ist.',
     'grammar_tip': 'Wen/was? → Akkusativ.'},

    {'id': 'gen_rel_029', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom',
     'data': {'text': 'Die Nachbarin, die jeden Morgen früh aufsteht, macht oft Lärm.',
              'english': 'The neighbour who gets up early every morning often makes noise.',
              'verbs': ['aufsteht', 'macht'], 'clause_type': 'relativsatz_nom',
              'sentence_a': 'Die Nachbarin macht oft Lärm.', 'sentence_b': 'Die Nachbarin steht jeden Morgen früh auf.'},
     'grammar_rule': '„Die“ ist Nominativ, weil es Subjekt im Relativsatz ist.',
     'grammar_tip': 'Subjekt = Nominativ.'},

    {'id': 'gen_rel_030', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk',
     'data': {'text': 'Der Kurs, den ich gerade mache, ist anspruchsvoll.',
              'english': 'The course that I am taking right now is challenging.',
              'verbs': ['mache', 'ist'], 'clause_type': 'relativsatz_akk',
              'sentence_a': 'Der Kurs ist anspruchsvoll.', 'sentence_b': 'Ich mache den Kurs gerade.'},
     'grammar_rule': '„Den“ steht im Akkusativ, weil es Objekt von „mache“ ist.',
     'grammar_tip': 'Maskulin Akkusativ = den.'},

    # ===== NEW: Level 3 (10) — Dativ + Präpositionen (life-related) =====
    {'id': 'gen_rel_031', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Der Kollege, dem ich vertraue, erklärt mir die Details.',
              'english': 'The colleague whom I trust explains the details to me.',
              'verbs': ['vertraue', 'erklärt'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Der Kollege erklärt mir die Details.', 'sentence_b': 'Ich vertraue dem Kollegen.'},
     'grammar_rule': '„Dem“ ist Dativ maskulin, weil „vertrauen“ den Dativ verlangt.',
     'grammar_tip': 'vertrauen + Dativ.'},

    {'id': 'gen_rel_032', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Die Person, mit der ich jeden Tag spreche, ist sehr hilfreich.',
              'english': 'The person I speak with every day is very helpful.',
              'verbs': ['spreche', 'ist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Die Person ist sehr hilfreich.', 'sentence_b': 'Ich spreche jeden Tag mit der Person.'},
     'grammar_rule': '„Mit der“ steht im Dativ nach „mit“.',
     'grammar_tip': 'mit + Dativ.'},

    {'id': 'gen_rel_033', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Aufgabe, der ich viel Zeit widme, ist nicht einfach.',
              'english': 'The task that I devote a lot of time to is not easy.',
              'verbs': ['widme', 'ist'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Aufgabe ist nicht einfach.', 'sentence_b': 'Ich widme der Aufgabe viel Zeit.'},
     'grammar_rule': '„Der“ ist Dativ feminin, weil „widmen“ den Dativ verlangt.',
     'grammar_tip': 'widmen + Dativ.'},

    {'id': 'gen_rel_034', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Der Ort, an dem ich oft arbeite, ist ziemlich ruhig.',
              'english': 'The place where I often work is quite quiet.',
              'verbs': ['arbeite', 'ist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Der Ort ist ziemlich ruhig.', 'sentence_b': 'Ich arbeite oft an dem Ort.'},
     'grammar_rule': 'Nach „an“ (Ort) steht Dativ: „an dem“.',
     'grammar_tip': 'an + Dativ = an dem.'},

    {'id': 'gen_rel_035', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Kollegin, der ich geholfen habe, hat sich bedankt.',
              'english': 'The colleague whom I helped thanked me.',
              'verbs': ['geholfen', 'habe', 'bedankt'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Kollegin hat sich bedankt.', 'sentence_b': 'Ich habe der Kollegin geholfen.'},
     'grammar_rule': '„Der“ ist Dativ feminin, weil „helfen“ Dativ verlangt.',
     'grammar_tip': 'helfen + Dativ.'},

    {'id': 'gen_rel_036', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Das Projekt, an dem ich gerade arbeite, ist sehr komplex.',
              'english': 'The project I am currently working on is very complex.',
              'verbs': ['arbeite', 'ist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Das Projekt ist sehr komplex.', 'sentence_b': 'Ich arbeite gerade an dem Projekt.'},
     'grammar_rule': '„An dem“ steht im Dativ, weil es um einen Ort/Bezug geht.',
     'grammar_tip': 'an + Dativ = an dem.'},

    {'id': 'gen_rel_037', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Leute, denen ich danke, haben mir viel gezeigt.',
              'english': 'The people whom I thank showed me a lot.',
              'verbs': ['danke', 'haben', 'gezeigt'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Leute haben mir viel gezeigt.', 'sentence_b': 'Ich danke den Leuten.'},
     'grammar_rule': '„Denen“ ist Dativ Plural, weil „danken“ Dativ verlangt.',
     'grammar_tip': 'danken + Dativ.'},

    {'id': 'gen_rel_038', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Die Firma, für die ich arbeite, ist international.',
              'english': 'The company I work for is international.',
              'verbs': ['arbeite', 'ist'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Die Firma ist international.', 'sentence_b': 'Ich arbeite für die Firma.'},
     'grammar_rule': 'Nach „für“ steht Akkusativ; daher „für die“.',
     'grammar_tip': 'für + Akkusativ.'},

    {'id': 'gen_rel_039', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep',
     'data': {'text': 'Der Termin, auf den ich warte, verschiebt sich oft.',
              'english': 'The appointment I am waiting for is often postponed.',
              'verbs': ['warte', 'verschiebt'], 'clause_type': 'relativsatz_praep',
              'sentence_a': 'Der Termin verschiebt sich oft.', 'sentence_b': 'Ich warte auf den Termin.'},
     'grammar_rule': 'Nach „auf“ (warten auf) steht Akkusativ: „auf den“.',
     'grammar_tip': 'warten auf + Akkusativ.'},

    {'id': 'gen_rel_040', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat',
     'data': {'text': 'Die Entscheidung, der ich zustimme, fühlt sich richtig an.',
              'english': 'The decision that I agree with feels right.',
              'verbs': ['zustimme', 'fühlt'], 'clause_type': 'relativsatz_dat',
              'sentence_a': 'Die Entscheidung fühlt sich richtig an.', 'sentence_b': 'Ich stimme der Entscheidung zu.'},
     'grammar_rule': '„Der“ ist Dativ feminin, weil „zustimmen“ Dativ verlangt.',
     'grammar_tip': 'zustimmen + Dativ.'},

    # ===== NEW: Level 4 (10) — Genitiv + "was" + Verschachtelung (life-related) =====
    {'id': 'gen_rel_041', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen',
     'data': {'text': 'Der Chef, dessen Feedback mir geholfen hat, hat viel Erfahrung.',
              'english': 'The boss whose feedback helped me has a lot of experience.',
              'verbs': ['geholfen', 'hat', 'hat'], 'clause_type': 'relativsatz_gen',
              'sentence_a': 'Der Chef hat viel Erfahrung.', 'sentence_b': 'Das Feedback des Chefs hat mir geholfen.'},
     'grammar_rule': '„Dessen“ steht im Genitiv maskulin und zeigt Besitz/Zugehörigkeit.',
     'grammar_tip': 'dessen = Genitiv maskulin/neutrum.'},

    {'id': 'gen_rel_042', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen',
     'data': {'text': 'Die Kollegin, deren Idee wir umgesetzt haben, war sehr praktisch.',
              'english': 'The colleague whose idea we implemented was very practical.',
              'verbs': ['umgesetzt', 'haben', 'war'], 'clause_type': 'relativsatz_gen',
              'sentence_a': 'Die Kollegin war sehr praktisch.', 'sentence_b': 'Wir haben die Idee der Kollegin umgesetzt.'},
     'grammar_rule': '„Deren“ ist Genitiv feminin und zeigt Zugehörigkeit.',
     'grammar_tip': 'deren = Genitiv feminin/plural.'},

    {'id': 'gen_rel_043', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was',
     'data': {'text': 'Alles, was ich heute verstanden habe, macht mich motivierter.',
              'english': 'Everything I understood today makes me more motivated.',
              'verbs': ['verstanden', 'habe', 'macht'], 'clause_type': 'relativsatz_was',
              'sentence_a': 'Alles macht mich motivierter.', 'sentence_b': 'Ich habe alles heute verstanden.'},
     'grammar_rule': 'Nach „alles“ nutzt man „was“ als Relativpronomen.',
     'grammar_tip': 'Alles + was.'},

    {'id': 'gen_rel_044', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was',
     'data': {'text': 'Das ist genau das, was ich für meinen Alltag brauche.',
              'english': 'That is exactly what I need for my everyday life.',
              'verbs': ['ist', 'brauche'], 'clause_type': 'relativsatz_was',
              'sentence_a': 'Das ist genau das.', 'sentence_b': 'Ich brauche das für meinen Alltag.'},
     'grammar_rule': 'Nach „das“ (= dasjenige) steht oft „was“.',
     'grammar_tip': 'das, was ...'},

    {'id': 'gen_rel_045', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt',
     'data': {'text': 'Die Kollegin, die das Modell gebaut hat, das wir jetzt testen, erklärt es im Meeting.',
              'english': 'The colleague who built the model that we are testing now explains it in the meeting.',
              'verbs': ['gebaut', 'hat', 'testen', 'erklärt'], 'clause_type': 'verschachtelte_relativsaetze',
              'sentence_a': 'Die Kollegin erklärt es im Meeting.',
              'sentence_b': 'Die Kollegin hat das Modell gebaut. Wir testen das Modell jetzt.'},
     'grammar_rule': 'Verschachtelte Relativsätze: jedes Verb steht am Ende seines Nebensatzes.',
     'grammar_tip': 'Jeder Relativsatz hat eigenes Verb am Schluss.'},

    {'id': 'gen_rel_046', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt',
     'data': {'text': 'Der Artikel, den ich gelesen habe, der mir neue Wörter gezeigt hat, war sehr nützlich.',
              'english': 'The article that I read, which showed me new words, was very useful.',
              'verbs': ['gelesen', 'habe', 'gezeigt', 'hat', 'war'], 'clause_type': 'verschachtelte_relativsaetze',
              'sentence_a': 'Der Artikel war sehr nützlich.',
              'sentence_b': 'Ich habe den Artikel gelesen. Der Artikel hat mir neue Wörter gezeigt.'},
     'grammar_rule': 'Mehrere Relativsätze werden getrennt; jedes konjugierte Verb steht am Ende des jeweiligen Relativsatzes.',
     'grammar_tip': 'Kommas + Verb am Ende.'},

    {'id': 'gen_rel_047', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen',
     'data': {'text': 'Das Team, dessen Hilfe ich schätze, arbeitet sehr zuverlässig.',
              'english': 'The team whose help I appreciate works very reliably.',
              'verbs': ['schätze', 'arbeitet'], 'clause_type': 'relativsatz_gen',
              'sentence_a': 'Das Team arbeitet sehr zuverlässig.',
              'sentence_b': 'Ich schätze die Hilfe des Teams.'},
     'grammar_rule': '„Dessen“ (Genitiv) zeigt Zugehörigkeit/Besitz an.',
     'grammar_tip': 'dessen = Genitiv maskulin/neutrum.'},

    {'id': 'gen_rel_048', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen',
     'data': {'text': 'Die Stadt, deren Rhythmus ich mag, hat viele Cafés.',
              'english': 'The city whose vibe I like has many cafés.',
              'verbs': ['mag', 'hat'], 'clause_type': 'relativsatz_gen',
              'sentence_a': 'Die Stadt hat viele Cafés.',
              'sentence_b': 'Ich mag den Rhythmus der Stadt.'},
     'grammar_rule': '„Deren“ ist Genitiv feminin und zeigt Zugehörigkeit.',
     'grammar_tip': 'deren = Genitiv feminin/plural.'},

    {'id': 'gen_rel_049', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was',
     'data': {'text': 'Alles, was ich am Wochenende geplant habe, hat sich geändert.',
              'english': 'Everything I planned for the weekend changed.',
              'verbs': ['geplant', 'habe', 'hat', 'geändert'], 'clause_type': 'relativsatz_was',
              'sentence_a': 'Alles hat sich geändert.',
              'sentence_b': 'Ich habe alles am Wochenende geplant.'},
     'grammar_rule': '„Alles“ → Relativpronomen „was“.',
     'grammar_tip': 'Alles + was.'},

    {'id': 'gen_rel_050', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt',
     'data': {'text': 'Der Kurs, den ich mache, der mir jeden Tag Struktur gibt, hilft mir sehr.',
              'english': 'The course I’m taking, which gives me structure every day, helps me a lot.',
              'verbs': ['mache', 'gibt', 'hilft'], 'clause_type': 'verschachtelte_relativsaetze',
              'sentence_a': 'Der Kurs hilft mir sehr.',
              'sentence_b': 'Ich mache den Kurs. Der Kurs gibt mir jeden Tag Struktur.'},
     'grammar_rule': 'Mehrere Relativsätze: jedes Verb steht am Ende seines Relativsatzes.',
     'grammar_tip': 'Komma + Verb am Ende.'},
]

