"""
Relative Clauses (Relativsätze) — Exercise Bank.

Tests Nominativ/Akkusativ/Dativ relative pronouns,
prepositions with relative pronouns, Genitiv (dessen/deren),
was/wo relative clauses, and nested relatives.
Exercise type: reconstruction
"""

RELATIV_BANK = [
    {'id': 'gen_rel_001', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom', 'data': {'text': 'Der Mann, der neben mir wohnt, ist Arzt.', 'verbs': ['wohnt', 'ist'], 'clause_type': 'relativsatz_nom', 'sentence_a': 'Der Mann ist Arzt.', 'sentence_b': 'Der Mann wohnt neben mir.'}, 'grammar_rule': '„Der“ steht im Nominativ, weil es Subjekt im Relativsatz ist und sich auf „der Mann“ (maskulin) bezieht.', 'grammar_tip': 'Relativpronomen richtet sich nach Funktion im Nebensatz.'},
    {'id': 'gen_rel_002', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk', 'data': {'text': 'Das Buch, das ich lese, ist spannend.', 'verbs': ['lese', 'ist'], 'clause_type': 'relativsatz_akk', 'sentence_a': 'Das Buch ist spannend.', 'sentence_b': 'Ich lese das Buch.'}, 'grammar_rule': '„Das“ steht im Akkusativ, weil es Objekt von „lese“ ist.', 'grammar_tip': 'Frage im Nebensatz: Wen oder was?'},
    {'id': 'gen_rel_003', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom', 'data': {'text': 'Die Frau, die dort arbeitet, kommt aus Spanien.', 'verbs': ['arbeitet', 'kommt'], 'clause_type': 'relativsatz_nom', 'sentence_a': 'Die Frau kommt aus Spanien.', 'sentence_b': 'Die Frau arbeitet dort.'}, 'grammar_rule': '„Die“ steht im Nominativ, da es Subjekt im Relativsatz ist.', 'grammar_tip': 'Subjekt im Nebensatz = Nominativ.'},
    {'id': 'gen_rel_004', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk', 'data': {'text': 'Der Film, den wir gestern gesehen haben, war lang.', 'verbs': ['gesehen', 'haben', 'war'], 'clause_type': 'relativsatz_akk', 'sentence_a': 'Der Film war lang.', 'sentence_b': 'Wir haben den Film gestern gesehen.'}, 'grammar_rule': '„Den“ steht im Akkusativ, da es Objekt von „gesehen haben“ ist.', 'grammar_tip': 'Maskulin Akkusativ = den.'},
    {'id': 'gen_rel_005', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_nom', 'data': {'text': 'Das Kind, das im Garten spielt, ist mein Neffe.', 'verbs': ['spielt', 'ist'], 'clause_type': 'relativsatz_nom', 'sentence_a': 'Das Kind ist mein Neffe.', 'sentence_b': 'Das Kind spielt im Garten.'}, 'grammar_rule': '„Das“ ist Nominativ, da es Subjekt von „spielt“ ist.', 'grammar_tip': 'Neutrum bleibt das.'},
    {'id': 'gen_rel_006', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk', 'data': {'text': 'Die Stadt, die wir besuchen, ist sehr alt.', 'verbs': ['besuchen', 'ist'], 'clause_type': 'relativsatz_akk', 'sentence_a': 'Die Stadt ist sehr alt.', 'sentence_b': 'Wir besuchen die Stadt.'}, 'grammar_rule': '„Die“ steht im Akkusativ, da es Objekt im Relativsatz ist.', 'grammar_tip': 'Plural oder feminin Akkusativ = die.'},
    {'id': 'gen_rel_007', 'module': 'relativ', 'type': 'reconstruction', 'level': 2, 'topic': 'relativpronomen_akk', 'data': {'text': 'Der Kuchen, den sie gebacken hat, schmeckt gut.', 'verbs': ['gebacken', 'hat', 'schmeckt'], 'clause_type': 'relativsatz_akk', 'sentence_a': 'Der Kuchen schmeckt gut.', 'sentence_b': 'Sie hat den Kuchen gebacken.'}, 'grammar_rule': '„Den“ ist Akkusativ, weil es direktes Objekt von „gebacken hat“ ist.', 'grammar_tip': 'Verb am Ende im Relativsatz.'},
    {'id': 'gen_rel_008', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat', 'data': {'text': 'Der Mann, dem ich geholfen habe, bedankt sich.', 'verbs': ['geholfen', 'habe', 'bedankt'], 'clause_type': 'relativsatz_dat', 'sentence_a': 'Der Mann bedankt sich.', 'sentence_b': 'Ich habe dem Mann geholfen.'}, 'grammar_rule': '„Dem“ steht im Dativ, da „helfen“ den Dativ verlangt.', 'grammar_tip': 'helfen + Dativ.'},
    {'id': 'gen_rel_009', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep', 'data': {'text': 'Die Kollegin, mit der ich arbeite, ist sehr nett.', 'verbs': ['arbeite', 'ist'], 'clause_type': 'relativsatz_praep', 'sentence_a': 'Die Kollegin ist sehr nett.', 'sentence_b': 'Ich arbeite mit der Kollegin.'}, 'grammar_rule': 'Nach Präpositionen steht das Relativpronomen im entsprechenden Kasus.', 'grammar_tip': 'mit + Dativ = mit der.'},
    {'id': 'gen_rel_010', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat', 'data': {'text': 'Die Kinder, denen wir helfen, sind dankbar.', 'verbs': ['helfen', 'sind'], 'clause_type': 'relativsatz_dat', 'sentence_a': 'Die Kinder sind dankbar.', 'sentence_b': 'Wir helfen den Kindern.'}, 'grammar_rule': '„Denen“ ist Dativ Plural, da helfen Dativ verlangt.', 'grammar_tip': 'Plural Dativ = denen.'},
    {'id': 'gen_rel_011', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep', 'data': {'text': 'Das Haus, in dem er wohnt, ist alt.', 'verbs': ['wohnt', 'ist'], 'clause_type': 'relativsatz_praep', 'sentence_a': 'Das Haus ist alt.', 'sentence_b': 'Er wohnt in dem Haus.'}, 'grammar_rule': 'Nach „in“ steht Dativ; daher „in dem“.', 'grammar_tip': 'Präposition bestimmt den Kasus.'},
    {'id': 'gen_rel_012', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat', 'data': {'text': 'Die Frau, der ich vertraue, wohnt hier.', 'verbs': ['vertraue', 'wohnt'], 'clause_type': 'relativsatz_dat', 'sentence_a': 'Die Frau wohnt hier.', 'sentence_b': 'Ich vertraue der Frau.'}, 'grammar_rule': '„Der“ ist Dativ feminin, da „vertrauen“ Dativ verlangt.', 'grammar_tip': 'vertrauen + Dativ.'},
    {'id': 'gen_rel_013', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_praep', 'data': {'text': 'Der Freund, mit dem ich gesprochen habe, reist morgen ab.', 'verbs': ['gesprochen', 'habe', 'reist'], 'clause_type': 'relativsatz_praep', 'sentence_a': 'Der Freund reist morgen ab.', 'sentence_b': 'Ich habe mit dem Freund gesprochen.'}, 'grammar_rule': '„Mit dem“ steht im Dativ nach der Präposition mit.', 'grammar_tip': 'mit + dem.'},
    {'id': 'gen_rel_014', 'module': 'relativ', 'type': 'reconstruction', 'level': 3, 'topic': 'relativpronomen_dat', 'data': {'text': 'Die Stadt, der wir viel verdanken, feiert Jubiläum.', 'verbs': ['verdanken', 'feiert'], 'clause_type': 'relativsatz_dat', 'sentence_a': 'Die Stadt feiert Jubiläum.', 'sentence_b': 'Wir verdanken der Stadt viel.'}, 'grammar_rule': '„Der“ ist Dativ feminin wegen „verdanken“.', 'grammar_tip': 'verdanken + Dativ.'},
    {'id': 'gen_rel_015', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen', 'data': {'text': 'Der Autor, dessen Buch ich lese, kommt aus Österreich.', 'verbs': ['lese', 'kommt'], 'clause_type': 'relativsatz_gen', 'sentence_a': 'Der Autor kommt aus Österreich.', 'sentence_b': 'Ich lese das Buch des Autors.'}, 'grammar_rule': '„Dessen“ steht im Genitiv maskulin und zeigt Besitz an.', 'grammar_tip': 'Genitiv Besitz = dessen/deren.'},
    {'id': 'gen_rel_016', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativpronomen_gen', 'data': {'text': 'Die Frau, deren Auto gestohlen wurde, ist verzweifelt.', 'verbs': ['gestohlen', 'wurde', 'ist'], 'clause_type': 'relativsatz_gen', 'sentence_a': 'Die Frau ist verzweifelt.', 'sentence_b': 'Das Auto der Frau wurde gestohlen.'}, 'grammar_rule': '„Deren“ ist Genitiv feminin und zeigt Zugehörigkeit.', 'grammar_tip': 'deren für feminin und Plural.'},
    {'id': 'gen_rel_017', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was', 'data': {'text': 'Alles, was er sagt, klingt logisch.', 'verbs': ['sagt', 'klingt'], 'clause_type': 'relativsatz_was', 'sentence_a': 'Alles klingt logisch.', 'sentence_b': 'Er sagt alles.'}, 'grammar_rule': 'Nach „alles“ verwendet man „was“ als Relativpronomen.', 'grammar_tip': 'Alles + was.'},
    {'id': 'gen_rel_018', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'relativsatz_was', 'data': {'text': 'Das ist genau das, was ich erwartet habe.', 'verbs': ['erwartet', 'habe', 'ist'], 'clause_type': 'relativsatz_was', 'sentence_a': 'Das ist genau das.', 'sentence_b': 'Ich habe das erwartet.'}, 'grammar_rule': 'Nach „das“ im Sinne von „dasjenige“ steht häufig „was“.', 'grammar_tip': 'das, was ...'},
    {'id': 'gen_rel_019', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt', 'data': {'text': 'Der Mann, der das Buch geschrieben hat, das ich lese, lebt in Berlin.', 'verbs': ['geschrieben', 'hat', 'lese', 'lebt'], 'clause_type': 'verschachtelte_relativsaetze', 'sentence_a': 'Der Mann lebt in Berlin.', 'sentence_b': 'Der Mann hat das Buch geschrieben. Ich lese das Buch.'}, 'grammar_rule': 'Mehrere Relativsätze beziehen sich jeweils auf ihr Bezugswort und stehen mit Verb am Ende.', 'grammar_tip': 'Jeder Relativsatz hat eigenes Verb am Schluss.'},
    {'id': 'gen_rel_020', 'module': 'relativ', 'type': 'reconstruction', 'level': 4, 'topic': 'verschachtelt', 'data': {'text': 'Die Stadt, in der ich studiert habe, die viele Parks hat, gefällt mir sehr.', 'verbs': ['studiert', 'habe', 'hat', 'gefällt'], 'clause_type': 'verschachtelte_relativsaetze', 'sentence_a': 'Die Stadt gefällt mir sehr.', 'sentence_b': 'Ich habe in der Stadt studiert. Die Stadt hat viele Parks.'}, 'grammar_rule': 'Mehrere Relativsätze werden durch Kommas getrennt; jedes Verb steht am Ende des jeweiligen Nebensatzes.', 'grammar_tip': 'Komma + Verb am Ende.'},
]

